### ISSUE TITLE
Input in Material Attribute is not checked

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#10]
If user adds a space or otherwise wrongly formats sizes in material attributes, the following or similar error occurs:

`Error: #<ArgumentError: Cannot convert "5 mm" to Length>
C:/Tmp/lairdubois-toolbox-sketchup-plugin/src/ladb_toolbox/ruby/model/material_attributes.rb:95:in 'to_l'`

**Comment by mobilarte** [comment]
if sizes may be entered without units, the plugin (Sketchup) assumes model units. If the user switches model units, the saved sizes in material attributes suddenly have a different meaning if they were previously saved without units.

**Comment by bbeaulant** [comment]
Maybe we need to disallow values without unit.

**Comment by CyberBLN** [comment]
> Maybe we need to disallow values without unit.

Or validate (and add the current model unit) + review before storing.

**Comment by bbeaulant** [comment]
> Or validate (and add the current model unit) + review before storing.

This is the current behavior :)
