### ISSUE TITLE
Sum not displayed

### ISSUE THREAD

**Issue by reshe** [lairdubois/lairdubois-opencutlist-sketchup-extension#100]
Hi Boris,

I have some parts that should show sum on length, it seams that there is a bug, the sum is not displayed.
![bug-sum-not-displayed](https://user-images.githubusercontent.com/4013583/58829029-754c8c00-864f-11e9-90c4-852d2458d925.jpg)

**Comment by bbeaulant** [comment]
Ho yes !
Fixed :)
