### ISSUE TITLE
Color Value in Material Definition not checked

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#105]
When I enter a color that is not valid like "#f", I get this error

Error: #<ArgumentError: Cannot find color named #f>
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/materials_controller.rb:246:in `color='
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/materials_controller.rb:246:in `update_command'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/materials_controller.rb:25:in `block in setup_commands'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:194:in `call'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:194:in `execute_command'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:387:in `block in create_dialog'
SketchUp:1:in `call'

**Comment by bbeaulant** [comment]
Fixed in last commit. Thank you for reporting it.
