### ISSUE TITLE
Surface or Finishes

### ISSUE THREAD

**Issue by AmadoSumbi** [lairdubois/lairdubois-opencutlist-sketchup-extension#107]
Hi, I really impressed with this extension. I’m working one of woodworking factory in Kuwait, the company uses imosAG software (CAD CAM 3D all in one licensed software) and I’m planning to open my own small woodwork shop in my country. I started to search alternative software in the internet and I found your extension. I would like to see if you can add some feature like the finishes, like for instance I have a board and the core material is MDF or Plywood or Solid wood or Chip board and for the finishes for front and back it would be, Laminate or Veneer or Paint or Formica. Similar what you made for the edges.

Thank you so much for the effort.

Best Regards,
Amado

I started to learn Ruby programming so I can also contribute to your project.

**Comment by bbeaulant** [comment]
Hi Amado,

I'm not sure to understand your needs. Do you want the extension returns the surface value of each panel to know the finish quantity ?

**Comment by AmadoSumbi** [comment]
Hi,
Something like that, but usually when we are ordering for production with the cutlist similar to the attached png file.

![Item9 SD402](https://user-images.githubusercontent.com/23437723/65798973-b119dd00-e17b-11e9-8dcc-25d8de544713.png)

**Comment by bbeaulant** [comment]
Ok, I understand. 
Currently maybe you can use labels on part to to something like this.
![Capture d’écran 2019-09-27 à 22 20 18](https://user-images.githubusercontent.com/156056/65799685-08687f00-e175-11e9-9437-ae3cd0b9221e.png)
![Capture d’écran 2019-09-27 à 22 19 24](https://user-images.githubusercontent.com/156056/65799686-08687f00-e175-11e9-8bd1-50eb2ecbd946.png)
![Capture d’écran 2019-09-27 à 22 19 12](https://user-images.githubusercontent.com/156056/65799687-09011580-e175-11e9-9ebb-f4a15d70b0b5.png)

**Comment by AmadoSumbi** [comment]
Ok, Thank you so much.
