### ISSUE TITLE
Components with double quotes break Cutting Diagram

### ISSUE THREAD

**Issue by SteveEasley** [lairdubois/lairdubois-opencutlist-sketchup-extension#110]
Components with double quotes in the name break the Cutting Diagram. For example `Drawer 2-7/16" Front`. When the quotes exist, the rendered Cutting Diagram just shows a gray shaded area where the part should should be. Also it adds some bizarre summary dimensions below the rendered diagram (which do not exist when the part has no quotes in the name).

![screenshot](https://live.staticflickr.com/65535/48929996661_c3decfb795_z.jpg)

**Comment by mobilarte** [comment]
I can confirm that this is a bug. Double quotes work fine in the parts list, but mess up the hover popup and the layout.

Thank you very much for reporting.

**Comment by bbeaulant** [comment]
Fixed in current [DEV](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz) release.
