### ISSUE TITLE
Edge bandings

### ISSUE THREAD

**Issue by pemitic** [lairdubois/lairdubois-opencutlist-sketchup-extension#111]
This plugin is great, but I would like to see an option to easily add edge banding on right click menu as check boxes or something like that.

**Comment by bbeaulant** [comment]
Thank you for this feedback @pemitic.
But as edge banding is controled by material applied on edge faces, you can use the Paint Bucket to apply edge banding on edge faces without opening OCL. Isn't it enought ?

**Comment by pemitic** [comment]
Yes, Thank You. 
I didn't know about that.
