### ISSUE TITLE
Piece identification

### ISSUE THREAD

**Issue by EL3737** [lairdubois/lairdubois-opencutlist-sketchup-extension#114]
It is essential to identify the pieces we work with.
I use Sketchup's "definition" field to bring clarity to complex designs.
It would be very important that in the cutting diagrams this field appears as it appears in "description" in "Part List".
I would greatly appreciate a chek to show the "definition" field in the diagrams.
Is there a way to hide the "part number" (needed internally) and be able to show "definition" on the cutting maps?
It is the field that really matters in the workshop.

Attached image of cut map that I use, note:
- set name: part name
- Color change for different edge bands
- measure to position disc (trimming + piece + blade tickness ...)

To suggest, it would also be good if the identical cutting diagrams do not repeat them, just indicate the number of identical sheets to be cut.

Thank you for assisting me.
Thank you for all the enhanced work.
![cut](https://user-images.githubusercontent.com/57797581/68951717-ef686b80-07be-11ea-93c2-81b762a8a5d9.jpg)

**Comment by bbeaulant** [comment]
Hi,

In the next release, a part list will be added to each sheet diagram. Wouldn't it be enough ?
![Capture d’écran 2019-11-16 à 10 50 01](https://user-images.githubusercontent.com/156056/68991425-21c9a580-085f-11ea-8285-e6ed61eb3dfb.png)

Using long name in cutting diagram bring some important problem of readability of the diagram if part are small. That why numbers are prefered.

> Color change for different edge bands

Yes, but where is the legend what color correspond to what ? And what color to use ? Predefined or real material color. But what about white color on white paper ?

> To suggest, it would also be good if the identical cutting diagrams do not repeat them

It's a good idea ! But if it's not enough clear for the user, I think it could be a source of mistake, no ?
