### ISSUE TITLE
npm install: gulp-util is deprecated

### ISSUE THREAD

**Issue by CyberBLN** [lairdubois/lairdubois-opencutlist-sketchup-extension#120]
Running `npm install` in `build` directory outputs

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

`npm ls gulp-util` shows that `gulp-zip@3.2.0` is the root dependency for this.

**Comment by bbeaulant** [comment]
Thanks to report it. It remove `gulp-util` dependency in last commit : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/commit/7eff8a7d08adeb8903a4beb68348ce5dc222d3e6
