### ISSUE TITLE
 "load errors" messagebox 

### ISSUE THREAD

**Issue by justintocci** [lairdubois/lairdubois-opencutlist-sketchup-extension#122]
I downloaded and installed Sketchup 8 for windows from this website: https://designerhacks.com/get-the-google-sketchup-free-download/

On startup of Sketchup 8 I get a "load errors" messagebox with an OK button.

![Captureerror](https://user-images.githubusercontent.com/14250339/72206545-e1e50000-3454-11ea-8bc7-3d83e84314c6.PNG)

The text of the error reads: 
Error Loading File ladb_opencutlist.rb undefined method `require_relative' for Ladb::OpenCutList:Module

I searched on Google and got no results. Let me know if I missed something.

**Comment by bbeaulant** [comment]
The minimal version of Sketchup required to execute OpenCutList is 2014.

Sketchup 8 is too old. Sorry.
