### ISSUE TITLE
How to add/change the theme color ?

### ISSUE THREAD

**Issue by ragupathis** [lairdubois/lairdubois-opencutlist-sketchup-extension#124]
At the moment, OpenCutList offers a single theme of colours, where we can add or change the few more colours to the theme?

**Comment by bbeaulant** [comment]
You want to rebrand OpenCutList ?

**Comment by ragupathis** [comment]
Not like that, we want it for internal use. The present colour scheme is not suitable for various reasons. So like to add a few more colours.

**Comment by bbeaulant** [comment]
⚠️ Ok, caution that for public use, you need to maintain the GPL license.

 🎨 Else, *.less files will be you friends.

**Comment by ragupathis** [comment]
Thanks @bbeaulant
