### ISSUE TITLE
Enregistrement matières OSX

### ISSUE THREAD

**Issue by baaaat** [lairdubois/lairdubois-opencutlist-sketchup-extension#125]
Hello, j'ai un petit bug sur OSX lorsque je veux enregistrer un .skm : 
Par exemple je veux enregistrer le materiau "contreplaqué" du plugin pièce de chez BLB.
Lorsque je crée une nouvelle pièce avec ce matériau et le plugin, les attributs ne sont pas reconnus par OCL.
En revanche, si je crée moi même un composant et que j'y colle la matière, les attributs sont bien reconnus mais le nom de la matière devient "auto" dans OCL

Sous windows, aucun problème, ça fonctionne parfaitement dans tous les sens !

**Comment by bbeaulant** [comment]
Salut,

Le fichier .skm, tu l'exportes à partir d'OCL ?
Quelle version d'OCL as-tu ?

**Comment by baaaat** [comment]
Oui bien sûr, exporté depuis OCL

J'ai la version 1.8.4 et ai eu le même bug sur sketchup 2019 et 2020

Le lun. 24 févr. 2020 à 09:12, Boris Beaulant <notifications@github.com> a
écrit :

**Comment by bbeaulant** [comment]
Ok, peux-tu envoyé le fichier .skp qui produit le bug et le fichier .skm que tu en exportes à l'adresse opencutlist@lairdubois.fr. Comme ça, je pourrai essayer de faire les teste dans le même contexte.
