### ISSUE TITLE
Cutlist for dimensional lumber

### ISSUE THREAD

**Issue by nivv** [lairdubois/lairdubois-opencutlist-sketchup-extension#128]
When working with dimensional lumber it would be useful to also get a cut list for those parts. This is because it would tell me how many 2x4's I should buy for example. The total length is not useful since the cuts can produce too much scrap.

Below screenshot might illustrate what I'm after more clearly.

<img width="371" alt="Skärmklipp 2020-04-22 14 20 12" src="https://user-images.githubusercontent.com/4033930/79981125-6d364e80-84a4-11ea-8ec4-538c3529465e.png">

A workaround I've been thinking about is labeling all dimensional lumber as sheet goods, but that seems silly.

**Comment by CyberBLN** [comment]
Hi @nivv,

we have already a feature request (https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/issues/87) and a working solution (https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/pull/121).

I have to check the last comments from @bbeaulant and maybe fix a little bit to get it ready for merge.

**Comment by bbeaulant** [comment]
Yes, this is a Work in Progress feature :)

**Comment by MichaelClaerbout** [comment]
Hi i just started using opencutlist so i don't know if i can be helpfull but i also use the  workaround with changing to sheets. Not sure why this would be silly? Its not alot work and once set easy to use... just my 2 cents! good luck

**Comment by nivv** [comment]
> Hi i just started using opencutlist so i don't know if i can be helpfull but i also use the workaround with changing to sheets. Not sure why this would be silly? Its not alot work and once set easy to use... just my 2 cents! good luck

Maybe a poor choice of words. Sure it works, but the print function makes no sense (1 page per 2x4 for example)

**Comment by mobilarte** [comment]
DEV build with cutting diagrams for dimensional lumber is available [here](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/master/dist/ladb_opencutlist-dev.rbz?raw=true).
