### ISSUE TITLE
Dialog Size Fix does not work on Windows

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#15]
The latest patch does not completely solve the problem. When maximizing/minimizing the window a few times, it can easily be verified that the windows gets 16 px smaller each time. This is probably due to the fact that on Windows the scrollbar is not overlapping the viewport like on Mac.

**Comment by bbeaulant** [comment]
I remember why I decide to stay with fixed dialog size ...

**Comment by mobilarte** [comment]
Why try to find out the size of the Dialog Window, when Sketchup is storing it for you!

I have a patch that should work on Mac.

The trick is to read the Width and Height from the registry just before the window is minimized, store the values in our own registry section/key to be able to resize the Dialog Window when the user maximizes the window.

[Patch for Dialog Window](https://github.com/mobilarte/lairdubois-toolbox-sketchup-plugin/commit/a91e2fe9ce1472b8ef79b862bc794aaeeafde059)

Now this does NOT work on Windows, because

1. Sketchup stores Width and Height of the Dialog Window in a DWORD in the registry
2. Sketchup.read_default will run the value through eval, which will choke on the DWORD

**Comment by mobilarte** [comment]
And here [Patch with BugFix](https://github.com/mobilarte/lairdubois-toolbox-sketchup-plugin/commit/607baa89161ea128ed0b776d0ba9433ae6122502) a commit with a fix for Sketchup 17 on Windows. I have also pushed the rbz file for you to test.

**Comment by bbeaulant** [comment]
Hmm ... your solution seems to be nice. But it doesn't work on Mac in this state.
On Mac, the pref key for Width and Height is just `DIALOG_PREF_KEY + '.Height'` in the root. No `WebCommonDialog_` prefix. but only on SU 2017. On previous version, I can't find dialog size in pref plist file ...

![Capture](https://cloud.githubusercontent.com/assets/156056/22197538/b6820ab4-e152-11e6-9271-d2091174f9c5.png)

Else if we only fetch size on minimize, what about the case of resizing dialog and closing SU without minimize the dialog ?

**Comment by bbeaulant** [comment]
It seems that previous version of SU (< 2017) that uses WebDialog instead of HtmlDialog doesn't store dialog size and position ...

**Comment by mobilarte** [comment]
1. WebDialog is deprecated, therefore just make dialog not memorize width/height
2. We can attach a closing block to HtmlDialog with set_can_close, catching the case of closing the dialog in the same manner as minimizing.

**Comment by bbeaulant** [comment]
We can't ignore Webdialog and then SU 2016 and lower users. I think it represents actualy the majority of users. SU 2017 need accelerated graphics card and the lastest OS version. Not every SU user want to switch there OS to use the last SU version.

The bad thing is that the JS `onresize` solution "works" on older version ...

**Comment by bbeaulant** [comment]
The other bad thing is that `Sketchup.read_default` function need a `section` parameter. And the value is stored without section. Empty string and nil parameter do not extract it.
