### ISSUE TITLE
Cross section not available

### ISSUE THREAD

**Issue by thatryan** [lairdubois/lairdubois-opencutlist-sketchup-extension#161]
HI there, first time trying to use this and am not sure what the issue is I am getting, can someone please advise?

For all my dimensional lumber in the parts list it says **Cross section not available**

<img width="2137" alt="Image 2020-06-08 at 11 17 25 AM" src="https://user-images.githubusercontent.com/26583/84065761-bc174500-a979-11ea-9628-91fbbf7517fe.png">

**Comment by bbeaulant** [comment]
Hi Ryan,

This is just because this cross section si not defined in material properties.

Add it to material and the warning will disappear :)

![Capture d’écran 2020-06-09 à 09 05 45](https://user-images.githubusercontent.com/156056/84117346-ad8c6480-aa31-11ea-8f41-11c69859654e.png)

**Comment by thatryan** [comment]
Thank you sir, I did that but maybe wrong. I am supposed to add in in actual not nominal is that right? So for a 1x3 board I would add cross section as .75 x 2.5 ?

**Comment by bbeaulant** [comment]
Or juste click on the "+" button. It adds values automaticaly to the material.
![Capture d’écran 2020-06-09 à 09 05 50](https://user-images.githubusercontent.com/156056/84184980-9a5bb200-aa8e-11ea-9990-ab351030c857.png)

**Comment by thatryan** [comment]
Ok I was totally misunderstanding. I thought had to add as nominal doh! Thank you so much!

**Comment by thatryan** [comment]
Terribly sorry, but may  I ask one follow up? Setting the dimensions fixed that and thank you, however some are missing from cutting diagram. In the parts list it recognizes I need 5 "Top Slats" in the Cherry, however in diagram it only shows a total of 3, and only uses 3 boards out of the 4 it says needed.?

<img width="1641" alt="Image 2020-06-09 at 3 21 00 PM" src="https://user-images.githubusercontent.com/26583/84206910-01647100-aa65-11ea-9193-7fe171abd6c1.png">

<img width="1681" alt="Image 2020-06-09 at 3 22 52 PM" src="https://user-images.githubusercontent.com/26583/84206975-235df380-aa65-11ea-8c62-c37b73a27e6f.png">

**Comment by bbeaulant** [comment]
Hi, it's normal, because the first bar is repeated 2 times. **(x2)**

<img width="1681" alt="84206975-235df380-aa65-11ea-8c62-c37b73a27e6f" src="https://user-images.githubusercontent.com/156056/84226739-eafcfa80-aae2-11ea-808a-7328ab045949.png">

You can change this behavior by changing display options :

![Capture d’écran 2020-06-10 à 06 25 21](https://user-images.githubusercontent.com/156056/84226895-52b34580-aae3-11ea-99d3-8db59edc3f5d.png)
