### ISSUE TITLE
Uncaught Type Error

### ISSUE THREAD

**Issue by thatryan** [lairdubois/lairdubois-opencutlist-sketchup-extension#164]
When clicking on cutting diagram for a sheet good list I am getting a popup error,

<img width="474" alt="Image 2020-07-02 at 1 45 25 PM" src="https://user-images.githubusercontent.com/26583/86407653-4d709300-bc6a-11ea-86be-28f9cca7c690.png">

**Comment by MartLeib** [comment]
Came here to report the same problem, I'm on Windows 10, SketchUp Make 2017.

**Comment by bbeaulant** [comment]
The next release 1.9.1 will fix this bug. You could test it here : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz
