### ISSUE TITLE
Parts with different dimensions (not in right angles parts)

### ISSUE THREAD

**Issue by pemitic** [lairdubois/lairdubois-opencutlist-sketchup-extension#172]
Hello,
Is it possible to support parts like this one, image below.
![TEST-1-2020-08-26_152852](https://user-images.githubusercontent.com/24562564/91310136-c515f680-e7b1-11ea-8f56-66ecc1311a5c.jpg)
In part list there is no banding on all sides and it doesn't show all dimensions.
![TEST-2-2020-08-26_152735](https://user-images.githubusercontent.com/24562564/91310157-cba46e00-e7b1-11ea-8ae8-2d250cf4c4c5.jpg)
Best Regards

**Comment by bbeaulant** [comment]
No, it isn't possible. OpenCutList know part only with **3 dimensions** (length, width, height). Then only rectangular parallelepiped is possible.
