### ISSUE TITLE
Impossible to generate the cutting diagram

### ISSUE THREAD

**Issue by theophae** [lairdubois/lairdubois-opencutlist-sketchup-extension#173]
I've just updated from 1.9.1 to 1.9.2, and with this new version I can no longer generate the cutting diagram on one of my projects. Something seems to be blocking, because I cannot regenerate de cut list or display the list of materials after trying to generate the cutting diagram.
I've tested to downgrade back to 1.9.1 and it is working again. To be sure I update again to 1.9.2 with the same result.

If there is any way to get some logs to see where it is blocking let me know and I'd be very happy to provide more info.

I've also tested the last plugin with another project and it is working, so it is no systematic.

**Comment by bbeaulant** [comment]
Outch, could you please send to <opencutlist@lairdubois.fr> a SKP file that generate the bug ?

> If there is any way to get some logs to see where it is blocking let me know and I'd be very happy to provide more info.

Else, open the **Ruby console** before generate and watch if something appear in the console.

**Comment by theophae** [comment]
Here are the log on the Ruby console:
`2020/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:52:in `block in setup_commands'
C:/Users/Théophane/AppData/Roaming/SketchUp/SketchUp 2020/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:196:in `execute_command'
C:/Users/Théophane/AppData/Roaming/SketchUp/SketchUp 2020/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:437:in `block in create_dialog'`

**Comment by theophae** [comment]
It works great with the new version 1.9.3
Thank you very much for quick fix.
