### ISSUE TITLE
generate cutting diagram still bugging

### ISSUE THREAD

**Issue by ZekeDelR** [lairdubois/lairdubois-opencutlist-sketchup-extension#174]
Just dowloaded and starting using v. 1.9.3 with sketchup make 2017 on mac el capitain. Excellent extension, thanks for all the hard work. I explored and played around for a few hours and suddenly the generate cutting diagrams function stopped working. Came here and noticed that this was a bug that was fixed earlier this day. I figured out it was because I had adjusted the parameter to stop labelling the pieces by letter. I came here and see that this "bug" was corrected as recently as this morning (3 sept), but I'm here to report that it's still an issue. Once I clicked the choice to name the pieces by letter the functionality of cutting diagrams became operative. Otherwise, it was impossible to generate a cutting diagram. Just so you know! Thanks for the developement of this awesome SU extension!

**Comment by bbeaulant** [comment]
Hi @ZekeDelR,

The bug was fixed this morning, but not published in final release.
You can download the current 1.9.4-dev build that fix this bug here : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz

**Comment by ZekeDelR** [comment]
Merci beaucoup! -de Lyon
