### ISSUE TITLE
Bug in Cutting Diagram Generation

### ISSUE THREAD

**Issue by jpr5** [lairdubois/lairdubois-opencutlist-sketchup-extension#175]
First, thanks for this totally awesome tool!  You guys are the BOMB.

Second, I am experiencing a bug in the cutting diagram layout functionality.  A few cuts' dimensions are swapped in the diagram. 
 [Here's a picture of it.](https://take.ms/Sh7Q0)

I've isolated it to [this model](https://www.dropbox.com/s/2sbugeaf1nleyux/OpenCutList%20Bug.skp?dl=0).  Select everything in it (bug doesn't manifest otherwise), then generate parts list, then cutting diagram for Knotted Plywood 2.  

Let me know if I can provide anything else!  Cheers.

**Comment by bbeaulant** [comment]
Hi Jpr5,

Yes, this is a bug in 1.9.3. It was reported and fixed last week in current **1.9.4-DEV** build. Currently not officialy released, but you can test it by using the DEV RBZ : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz

Thank for reporting and have a nice day !
