### ISSUE TITLE
Single shopping list

### ISSUE THREAD

**Issue by KevinFauth** [lairdubois/lairdubois-opencutlist-sketchup-extension#176]
Like everyone else - awesome extension.

I'm just not sure how to export a shopping list. Is there a way I can just get one output that shows what I need when I run to the lumber store?

In the summary at the top of the Parts List, it outlines the number of parts I'll end up with - but it's only when I run a cutting diagram do I finally get to find out how many 2x4's I actually need to buy. Which I guess it fine, but when using a variety of dimensional lumber, I have to generate cutting diagrams for each material. Then draw up my own shopping list.

I keep feeling like I'm missing something simple - since it seems like an obvious feature. Help direction would be appreciated!

As an aside, it would be helpful to attach a cost to each piece of lumber so I can see what the total cost of the project would be (even be able to add different sizes/stores/etc to find the best price).

**Comment by bbeaulant** [comment]
Hi Kevin,

I understand your need but currently this is not possible in One user action, sorry.
Creating "report" will certainly be the next key feature of OpenCutList. But from now you have to do it manualy. And compute cost in an other software.

**Comment by KevinFauth** [comment]
Thanks Boris, I get ya! Keep up the good work!
