### ISSUE TITLE
little Thing

### ISSUE THREAD

**Issue by Carpspb** [lairdubois/lairdubois-opencutlist-sketchup-extension#187]
What I found: there is an "r" missing
![Screenshot 2020-10-02 110246](https://user-images.githubusercontent.com/46330843/94906551-f794cc80-049e-11eb-8ac1-7232c3e4221d.jpg)
It should be written: Herunterladen instead of Herunteladen

**Comment by bbeaulant** [comment]
Hi Carpspb,

Thank you for reporting this typo.
Fixed in source code 👍 

Have a nice day
