### ISSUE TITLE
I want even the small pieces to show the dimensions on the diagram.

### ISSUE THREAD

**Issue by iya5598** [lairdubois/lairdubois-opencutlist-sketchup-extension#194]
![캡처](https://user-images.githubusercontent.com/72940922/96167966-11ccb100-0f5b-11eb-9615-8b910004c740.PNG)

Thank you for letting me use a good program. I have a suggestion.
The dimensions of K+ and AQ+ are not shown in the image above.
Even if I draw a large diagram, I hope the dimensions of the small piece are displayed.
In fact, when cutting, it is very inconvenient because the dimensions are not visible when you print the diagram and cut it while looking at the diagram.
I wish I had good news. 
Thank you for your hard work.

**Comment by mobilarte** [comment]
In the cutting diagram configuration tab, there is an option to display the list of parts of each panel right below each cutting diagram (third tab of the window). When parts become really small, there is no way to overlay their dimensions without creating a mess.

In the configuration, identical panels can also be grouped, so you don't have to print several pages for the same cutting diagram.

**Comment by bbeaulant** [comment]
We may be able to try to improve dimensions display for "K+" parts. But for AQ+, as @mobilarte says, its impossible to have a readable diagram with dimensions.

As @mobilarte says, the best choice is to activate the display Part List option.

![Capture d’écran 2020-10-16 à 13 28 16](https://user-images.githubusercontent.com/156056/96253304-a82cc100-0fb3-11eb-9382-5eb09f86cb9a.png)
![Capture d’écran 2020-10-16 à 13 28 37](https://user-images.githubusercontent.com/156056/96253305-a9f68480-0fb3-11eb-8e6c-56711a7e5937.png)

**Comment by iya5598** [comment]
Yes, I don't think I can make a small piece. But I hope K+ will be improved

**Comment by iya5598** [comment]
I already know the activation of the parts list.

**Comment by DamirGatin** [comment]
![2020-10-14_01-54-42 (4)](https://user-images.githubusercontent.com/37908268/96376631-94db4a80-1199-11eb-9c4c-15ad6ad5e4bf.png)
If possible, make it possible to move the horizontal label from the middle of the part to the right.

**Comment by bbeaulant** [comment]
@DamirGatin thank you.
But after a reflexion we won't arrange text like you want on future release.
Doing this do not really solve problem and bring new one. The technology we use do not permit to know the true width of a text in pixels with a specified front and size. As it's not a monospaced font and it depends of the Operating System.
And in my usage I encountered the problem that if the dimension is not write in the same place on each part, it's quit confuse.

Else, if you want to play with it, it's here : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/8e421f6216c4e650cddbaed31b5096289280d5dd/src/ladb_opencutlist/twig/tabs/cutlist/_slide-cuttingdiagram-2d.twig#L263

**Comment by bbeaulant** [comment]
@iya5598, in the last 1.9.6 I changed a little the strategy to hide dimensions. Now width and length are independant and each one is displayed or hide if it has enough room to. Then on you K+ parts, I think that width will be visible. But length stay hidden.
_But for this, you need the hide the unit format in SketchUp options._

**Comment by DamirGatin** [comment]
And how to install new _slide-cutdiagram-2d.twig?

**Comment by bbeaulant** [comment]
You have to recompile according to those instructions : 

https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/master/docs/01-development.md

**Comment by iya5598** [comment]
> @ iya5598 , 지난 1.9.6에서 차원을 숨기는 전략을 약간 변경했습니다. 이제 너비와 길이는 독립적이며 충분한 공간이 있으면 각 항목이 표시되거나 숨겨집니다. 그러면 K + 파트에 너비가 보일 것 같아요. 그러나 길이는 숨겨져 있습니다.
> _그러나이를 위해서는 SketchUp 옵션에서 단위 형식 숨기기가 필요합니다._

Thank you for your attention.
