### ISSUE TITLE
Can I automatically transmit the sheet type and size for the sheet material?

### ISSUE THREAD

**Issue by DamirGatin** [lairdubois/lairdubois-opencutlist-sketchup-extension#198]
And where is this information stored after manual assignment?

**Comment by mobilarte** [comment]
Could you please be more specific?

In OCL you define Material, which can have the property "Sheet Good", with parameters like thickness and sheet size. For groups of parts with same material and thickness a cutting diagram can be computed. 

The properties of the material are stored inside the SketchUp file.

**Comment by DamirGatin** [comment]
![2020-10-28_13-52-39](https://user-images.githubusercontent.com/37908268/97413776-04cd9b80-1925-11eb-9c81-cd1d4f2fbf06.png)
How are these IDs created? I would like to record information here so that your plugin automatically detects the type and size of the material.

**Comment by bbeaulant** [comment]
Hi,

> I would like to record information here so that your plugin automatically detects the type and size of the material.

What kind of information ?
What do you mean by "automatically detects the type and size of the material" ? 

> How are these IDs created?

It's a hash (MD5) generated from material unique identifier and its section if a type is defined.
This identifier is not reversible and change if type or size change.

**Comment by DamirGatin** [comment]
Can I recreate the same ID? Tell me in which file it is generated. This is necessary so that I write these attributes with the ID to the model and the plugin doesn't ask about the type of material. Thanks.

**Comment by bbeaulant** [comment]
The group ID is generated here : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/6cb70395d2f43f93fe5502eb96dbd1b964ebee19/src/ladb_opencutlist/ruby/model/cutlist/groupdef.rb#L39

This ID is the ID of a group. And a group is a set of parts with the same material and thickness (or section if material type is "dimensional").

But it is generated from Material UUID that can change if it is not unique in the model.

> This is necessary so that I write these attributes with the ID to the model and the plugin doesn't ask about the type of material.

I'm not sur to understand what you need...

**Comment by mobilarte** [comment]
No reply!
