### ISSUE TITLE
Chipboard working (real view for edges)

### ISSUE THREAD

**Issue by vegas75** [lairdubois/lairdubois-opencutlist-sketchup-extension#203]
Hello! This is a great plugin! Thanks! But I am missing the visual effect without an edge bandings when working with chipboard or MDF, like this:
![Снимок экрана 2020-11-03 в 21 39 14](https://user-images.githubusercontent.com/73779261/98034420-a4a49100-1e1f-11eb-8e1e-87b82642627f.png)
Is it possible to make an edge fill the default? This makes it easier to visually control the presence of a PVC edge, etc.
Thanks in advance!

**Comment by bbeaulant** [comment]
As I can see you do not apply any edge band material on your board's edges.

> Is it possible to make an edge fill the default?

I'm not sur to understand what you need.

**Comment by vegas75** [comment]
It looks like the plugin work by adding material to the workpiece. It looks like the plugin work by adding material to the workpiece. This panel looks like the edge is already glued on
![Снимок экрана 2020-11-03 в 22 24 29](https://user-images.githubusercontent.com/73779261/98037212-e8999500-1e23-11eb-97bc-52a39f486fbc.png)

**Comment by vegas75** [comment]
Do you speak russian?

**Comment by mobilarte** [comment]
Нет, мы не говорим по-русски!

нужно добавить материал "кромки", после чего можно выбрать его для кромок.
вы можете переключить плагин на русский, если это вам поможет!

Я использую http://www.deepl.com и http://www.translate.ru

**Comment by bbeaulant** [comment]
> Do you speak russian?

No, sorry.

---

You have to create 2 materials :
- 1 of type "Sheet goods"
- 1 of type "Edge banding"

![Capture d’écran 2020-11-03 à 21 37 17](https://user-images.githubusercontent.com/156056/98038057-ccdec080-1e1c-11eb-9857-2386b32dcc50.png)

You apply the sheet material on your part instance.

![Capture d’écran 2020-11-03 à 21 37 08](https://user-images.githubusercontent.com/156056/98038059-cd775700-1e1c-11eb-820b-f9184f0c2c1c.png)

And apply the edge material on the faces that represents edges.

![Capture d’écran 2020-11-03 à 21 37 25](https://user-images.githubusercontent.com/156056/98038053-ca7c6680-1e1c-11eb-8c4b-dc0018ec2a30.png)

**Comment by vegas75** [comment]
Your plugin is great! It is understandable in any language! :)
Now I am very tired, tomorrow I will try to explain everything clearly. Thank you for your interest in my question!!!

**Comment by vegas75** [comment]
Dear developer! In real life, a chipboard panel looks like this:
![Снимок экрана 2020-11-14 в 11 00 06](https://user-images.githubusercontent.com/73779261/99143756-aadd0d80-2668-11eb-9561-25a8195e34ed.png)
It would much more suitable if I could see your plugin work  in stages, as follows:
Step 1. Create a dynamic component:
![Снимок экрана 2020-11-14 в 11 05 55](https://user-images.githubusercontent.com/73779261/99143846-803f8480-2669-11eb-825b-790247a01744.png)
Step 2. Texture applied by OCL:
![Снимок экрана 2020-11-14 в 11 14 05](https://user-images.githubusercontent.com/73779261/99143951-94d04c80-266a-11eb-93b6-91af542cfcc0.png)
Step 3. One edge applied by OCL:
![Снимок экрана 2020-11-14 в 11 17 37](https://user-images.githubusercontent.com/73779261/99144009-0d370d80-266b-11eb-88f6-528ea9d61bbc.png)
etc.
Is it possible?

**Comment by bbeaulant** [comment]
Hi @vegas75,

Currently, it's possible to have this result, but it's not the job of OCL to manage the graphical aspect.

💡  You can apply a material on the component instance and one other on the volume faces.

OCL primarily uses material applied on part instances. Then you can apply the material with grey texture (configured as _sheet good_) on your instance and edit your component and apply an other material with wood texture on edge's faces.
This second material should be configured without type.

After that you need a third material with grey texture and configured as _Edge banding_ that you can apply on banded edges.

**Comment by vegas75** [comment]
Yes, I do that now. Thank you very much for your answer and for your software product!
