### ISSUE TITLE
problem of duplication of material

### ISSUE THREAD

**Issue by CarlosSanto** [lairdubois/lairdubois-opencutlist-sketchup-extension#212]
Hello!

How to solve this problem of duplication of material ?, all the components are 15mm thick, but when I apply the material to the components they are divided even with the same thickness, and the material is also duplicated.

                               **Parts with 15mm of thickness;**

![Lista Peças sem material](https://user-images.githubusercontent.com/74726431/99697981-03e4e100-2a6f-11eb-94eb-1ac3dc43df2b.JPG)

                                                         **Materials**

![Material 15mm](https://user-images.githubusercontent.com/74726431/99698346-6e961c80-2a6f-11eb-94f5-3ca25c6a44ae.JPG)

                                                    **Materal duplicate**

![Materais diferentes](https://user-images.githubusercontent.com/74726431/99698450-938a8f80-2a6f-11eb-8dc3-191189fc9358.JPG)

                                                  **Same thickness in different cutting planes**

![Materiais diferentes](https://user-images.githubusercontent.com/74726431/99698724-df3d3900-2a6f-11eb-96ad-3bd62ca62baa.JPG)

How to make the program recognize all the parts with the same thickness.

Observation; the pieces were made individually; I have already erased and redone, but it did not solve.

**Comment by mobilarte** [comment]
Hi,

Increase the precision of the units, you can do it by clicking the units (see picture). Your parts do probably not have exactly the same thickness.

![99698450-938a8f80-2a6f-11eb-8dc3-191189fc9358](https://user-images.githubusercontent.com/24858423/99700269-3d2f4800-2a93-11eb-986e-56e3ef60cc3c.jpg)

**Comment by bbeaulant** [comment]
If you upgrate to the last [1.9.9](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist.rbz), you will see the problem because OCL now permit to know the real size of your parts.

Some parts of your model do not exactly mesure 15mm (but maybe 14,9998mm). As @mobilarte says increase the precision of your model and you will see it.
