### ISSUE TITLE
Right click on highlighted part does not work

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#213]
On Windows Sketchup 17.2 / OCL 1.9.9 it produces this message on the ruby console:

Error: #<NoMethodError: undefined method `id' for nil:NilClass>
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/tool/highlight_part_tool.rb:252:in `block in build_menu'
SketchUp:1:in `call'

**Comment by bbeaulant** [comment]
Zut !

**Comment by bbeaulant** [comment]
Could you try with the last build ?

**Comment by mobilarte** [comment]
1. Menu build-up with @hover_part and @hover_part.id

entering #<Ladb::OpenCutList::Part:0x000195c79187d8>
m1 #<Ladb::OpenCutList::Part:0x000195c79187d8> => 3069c201cb8e4b89d2e35f97f08f3c71
m2 #<Ladb::OpenCutList::Part:0x000195c79187d8> => 3069c201cb8e4b89d2e35f97f08f3c71
m3 #<Ladb::OpenCutList::Part:0x000195c79187d8> => 3069c201cb8e4b89d2e35f97f08f3c71
m4 #<Ladb::OpenCutList::Part:0x000195c79187d8> => 3069c201cb8e4b89d2e35f97f08f3c71
validate m1

When right clicking on first, second and last menu item => nothing happens, it never executes Plugin.instance.execute_dialog_command_on_tab.

You will notice that validate is called twice, once for the menu build-up and just before executing.
In the second call, @hover_part does not exist, hence

validate m1 [#<Ladb::OpenCutList::Part:0x000195c73cd2d8>]
validate m1 []

2. When clicking on third menu, it becomes obvious that @hover_part is nil, because it does not have the gorup method.

Error: #<NoMethodError: undefined method `group' for nil:NilClass>
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/tool/highlight_part_tool.rb:273:in `block in build_menu'
SketchUp:1:in `call'
parameters { part_id: '3069c201cb8e4b89d2e35f97f08f3c71', tab: 'size_increase', dontGenerate: true }

**Comment by bbeaulant** [comment]
Hmm ... maybe it's a problem of context. SU do not pass variable context in second call.

**Comment by mobilarte** [comment]
Yes, I don't understand why validate is called twice.

**Comment by bbeaulant** [comment]
On Mac version of SU, even on SU 2017, validate proc is call only once on menu build...

Only when clicking on third menu, not others ??

**Comment by mobilarte** [comment]
validate is called twice for all menus. Maybe because SU 17.2 on Windows, SU 17.3 on Mac!

**Comment by bbeaulant** [comment]
I've got SU 17.1 MAC.
And if you try with the last commit it crashes ?

**Comment by mobilarte** [comment]
Doesn't crash but does nothing.

The fix is probably along these lines:

```
# get id during build_menu context not at runtime
my_id = "'" + "#{@hover_part.id}" + "'"

m1 = menu.add_item(Plugin.instance.get_i18n_string('tab.cutlist.edit_part_properties')) {
  Plugin.instance.execute_dialog_command_on_tab('cutlist', 'edit_part', "{ part_id: " + my_id + ", tab: 'general', dontGenerate: true }")
}
 _ = menu.set_validation_proc(m1) {
          my_other_id = my_id
          puts("validate m1 [#{my_other_id}]")
          if my_other_id
            MF_ENABLED
          else
            MF_GRAYED
          end
        }

**Comment by bbeaulant** [comment]
Hmm, but why passing `my_id` works when `@hover_part` not ... ?

**Comment by mobilarte** [comment]
Because the string gets evaluated earlier/later. The block of the menu is not evaluated in the build_menu context.

**Comment by bbeaulant** [comment]
Ok, then the problem is not in validation block.

**Comment by bbeaulant** [comment]
Ok, and with this : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/3c362c5c97e59474d27e4a1dbb8935613014c55f/src/ladb_opencutlist/ruby/tool/highlight_part_tool.rb#L241 ?

**Comment by mobilarte** [comment]
Seems to work! Thank you.

**Comment by bbeaulant** [comment]
Nice !
