### ISSUE TITLE
OpenCutList Does not support groups

### ISSUE THREAD

**Issue by yvan-r** [lairdubois/lairdubois-opencutlist-sketchup-extension#215]
when trying to generate part list the following error occurs:
	
"Darn!
No instance of a visible component was detected in your scene."

**Comment by mobilarte** [comment]
Yes, we do not support groups for many reasons. The parts must be instances of a component.

**Comment by yvan-r** [comment]
Any plans to support groups in the future?

**Comment by mobilarte** [comment]
We have not found a single good argument in favor of groups. Drawing in SketchUp with groups only is rarely a good idea.

Why would you want to be able to use groups?

**Comment by yvan-r** [comment]
I use Profile Builder 3 to create window assemblies.
Profile builder does not support components for profile Members.
I also use ABF plugin for cabinets assemblies. ABF plugin does not support components.

Why not support both groups & components?
Groups are also instanced when duplicated just like components, they are made unique only when modified.

**Comment by bbeaulant** [comment]
> Groups are also instanced when duplicated just like components, they are made unique only when modified.

Yes they have virtualy the same definition until the user modify them. But there's not clear way for user to understand why this change appear. And the definition name is hidden from SketchUp UI.

> ABF plugin does not support components.

Sorry for that.
