### ISSUE TITLE
Drillings on sheet materials

### ISSUE THREAD

**Issue by agav** [lairdubois/lairdubois-opencutlist-sketchup-extension#219]
Hi, I usually order sheet woods in local company here in Kyiv. 
They offer services of cutting materials, and applying edge bindings. 
With your plugin I can easily make such orders. But also they can make drillings (and other processing) on ordered parts.
I provide them parameters of each drilling on each detail - e.g. x, y, depth, diameter

I always calculate these params manually and it takes lot of time and yields a lot of mistakes. But I think I have an idea how to automate it with help of your plugin.

The idea is to use Sketchup components glued to face with cut openings on them, and provide list of those components on each detail

I created a little sample project and some code (draft) in 
[surface_components.zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/5625641/surface_components.zip)

I would appreciate if you take a look on it and decide if such concept is interesting for you, or it just a waste of time. 

![FEABaq1C86](https://user-images.githubusercontent.com/668614/100801330-7e7b0c80-3430-11eb-8be5-a627af02d883.png)

**Comment by bbeaulant** [comment]
Hi @agav,

Really nice improvement ! And well integrated. Thank you for your patch.
I just wondering if "part properties" is the best place to display those values.

My other question is that the user can put cut opening components that are not necessary drill holes. And then how to detect or display the difference ?

**Comment by agav** [comment]
Regarding "part properties" I don't know, just found that place the most easy to embed to ).

Yes, user can put whatever they want on a face. I even think that the objects they put  shouldn't necessarily have cut openings on them (only gluing to face is enough). The plugin just provides list with name, side and coordinates of that objects (I suppose adding also component attributes) - that list could be very helpful while assembling details. As you see in sample I added all needed information about drillings into components name. Also this feature could be implemented to be turned off or on for the whole model / material / or component itself.

Regarding my provider. They have web-UI where I can add and edit holes and other operations with with my mouse. And they allow to export/import to/from xml file with their proprietary format. Here is the example

![image](https://user-images.githubusercontent.com/668614/100846233-f1af6d80-3486-11eb-84ca-3c8532d726dc.png)

So if I have parsable export from your plugin I will be able to convert it such file for them. That's why I consider of adding json/yaml or xml export to your plugin - I will open other issue for this ).

**Comment by bonchi197** [comment]
@agav I think that xm/json file is great because is like a standard in data exchange between system.

I would like to add also csv file. In Poland a lot of companies uses software with use this extention to import data about drills.

**Comment by firkeuf** [comment]
Is it possible to add this feature to the release? And it will be great to have the same for Solid Wood and Dimensional materials.
Thanks

**Comment by bbeaulant** [comment]
@firkeuf, this kind of feature is not (and maybe never be) planned. As far as I know there no standard to export this kind of data.

But since version 6.0, you can export part geometry to DXF (or SVG) format, then use or write your own external tool to analyze that geometry.
The exported DXF or SVG contains ellipses to represent holes. So, most software can easily extract the coordinates and radius of the hole.
