### ISSUE TITLE
One entity not being correctly recognized as 2x4

### ISSUE THREAD

**Issue by josh-m-sharpe** [lairdubois/lairdubois-opencutlist-sketchup-extension#225]
I apologize I'm fairly new to SketchUp and Open Cut List.  It seems that this one stick of wood should be able to be cut from a 2x4 (1.5x3.5), but OpenCutList insists I need a 3 9/16" x1 1/2".  I think the issue has something to do with the orientation of the item. Maybe?

In my screenshots below I show various ways of measuring it - and all dimensions are less than 3 1/2". I even converted the model to Decimal and confirmed it wasn't some rounding error (since I saw that issue elsewhere on the internets).  
The sketchup file should be available on google drive [here](https://drive.google.com/file/d/1oZ4SlQb4axl6guFNcCWx92Er1_iJlf2o/view?usp=sharing).

Am I doing something wrong?  Thanks!

![OpenCutList_by_L_Air_du_Bois_-_1_9_9](https://user-images.githubusercontent.com/39473/101985731-c3d0e280-3c57-11eb-9bf4-39261c689397.jpg)
![OpenCutList_by_L_Air_du_Bois_-_1_9_9_and_Wood_Rack_skp_-_SketchUp_Make_2017](https://user-images.githubusercontent.com/39473/101985732-c3d0e280-3c57-11eb-9a3c-d7ba129070d2.jpg)
![Wood_Rack_skp_-_SketchUp_Make_2017](https://user-images.githubusercontent.com/39473/101985859-7ef97b80-3c58-11eb-8f69-b2ffe06345bb.jpg)
![Wood_Rack_skp_Info_and_OpenCutList_by_L_Air_du_Bois_-_1_9_9](https://user-images.githubusercontent.com/39473/101985730-c3384c00-3c57-11eb-8899-8c04122b43a3.jpg)

**Comment by bbeaulant** [comment]
Hi,

**This a problem of axes orientation.**

OpenCutList couldn't detect the part direction. You have to setup it manualy along components axes.
And OCL doesn't know the part shape. It only knows the **bounding box**. The bounding box is the blue box drawed around the part when you select it.

![Capture d’écran 2020-12-12 à 15 15 46](https://user-images.githubusercontent.com/156056/101986210-fd701080-3c8c-11eb-86e8-396e6c0be361.png)

Length, With and Thickness are mesured by OpenCutList along this bounding box. In you model you can see difference between the two parts. One have axes oriented as you want and the other not.

The solution is to edit the first part and change its axes orientation with red along the main edge.

This couldn't be automatique.
