### ISSUE TITLE
Add nb. of parts in the summary of the cutting diagram

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#229]
When cutting more than one panel, counting the total number of parts that have been cut helps verifying that all the parts have indeed been cut.

Currently, one needs to add up the number of parts per panel to get the overall total.

Proposal: add a column or at least display the total number of parts in the summary of the cutting diagram.

**Comment by bbeaulant** [comment]
Hi,

Something like that  ?

![Capture d’écran 2021-02-09 à 09 06 53](https://user-images.githubusercontent.com/156056/107333844-4807e080-6ab6-11eb-9bf8-7086d5044510.png)

**Comment by mobilarte** [comment]
Yes, perfect! Thank you.

**Comment by bbeaulant** [comment]
Cool :)
