### ISSUE TITLE
Make origin of cutting diagram configurable

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#230]
Currently the top left corner is the origin of the cutting diagram.

Proposal: make the origin configurable, top left or bottom left corner for the y-axis.

**Comment by bbeaulant** [comment]
Feature implemented in last commit (https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/commit/786d1a6b0209eb04fca87158306de32d49970a17)

It will be available in next release.
