### ISSUE TITLE
Make the UI more compact

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#231]
On smaller screen, OCL takes up a lot of space. Investigate possibilities to make the interface more compact.

[adjust size/compactness of interface](https://opencollective.com/lairdubois-opencutlist-sketchup-extension/conversations/adjust-size-compactness-of-interface-0pxxobpy)

**Comment by bbeaulant** [comment]
Feature added as global UI zoom. 3 levels (100%, 90%, 80%).
Need some tests.

![Capture d’écran 2021-01-25 à 09 43 03](https://user-images.githubusercontent.com/156056/105681755-dba3b380-5ef1-11eb-9dc9-10cadec40820.png)

**Comment by bbeaulant** [comment]
It bugs with material **ColorPicker** and axes **Sorter** ... need to find an other solution :(

**Comment by mobilarte** [comment]
This feature will not be added in Version 2.0, causing too much technical trouble.
