### ISSUE TITLE
Color Picker not working

### ISSUE THREAD

**Issue by LeeDumond** [lairdubois/lairdubois-opencutlist-sketchup-extension#233]
In Sketchup 2017 for Windows, in the form that you use to create a new Material, the color picker does not work. I am able to type in hex values though. This is for OCL 1.9.10, I just installed it today.

**Comment by mobilarte** [comment]
I cannot confirm this behaviour for OCL 1.9.10.  But while checking this, I noticed that the color picker does not work anymore in version 2.0.0 when using a font size other than normal (small, tiny), which not only changes the font size but also does a html zoom.
We will investigate this.

**Comment by bbeaulant** [comment]
Hi @LeeDumond,

Thanks for reporting this. I know that the color picker display wrong on Windows with SU < 2016 and older, because the color picker library is not compatible with Internet Explorer. Is it what you have ?

@mobilarte ... damned !

**Comment by bbeaulant** [comment]
A new one will be available in 2.0.
