### ISSUE TITLE
Summarize Volume and seperate units in csv export

### ISSUE THREAD

**Issue by ganafets82** [lairdubois/lairdubois-opencutlist-sketchup-extension#239]
Hi!
Just found this beautiful extension and it works just fine!
I used it for a framing construction for a shed.

It would be great if the volumes of each used material would be summerized. So I can see how much m³ wood I used in total and can calculate the weight.

I thought I can calculate this with the exported csv, but the numbers are exported together with the units, so I cant do without extra efford.
It would be better to save the csv either without unit, or separated from the actual dimensions.

Thanks for your work!

Stefan

**Comment by mobilarte** [comment]
Hi Stefan,

If you remove the units from being displayed in the Model Info -> Units, they will not appear in the CSV export, nor will they show up in the Parts List.

The volumes are displayed in the summary at the top of the Parts List.

**Comment by ganafets82** [comment]
Hi.
removing the units worked! Thanks!

The volumes are displayed at the top, but for every dimension each and not in total for each material. Would be nice to have it in total in the print output. If I have a dozen different wood dimensions, I have to type it in the calculator for every dimension (or export as csv and calculate there as a workaround).

**Comment by mobilarte** [comment]
I see what you mean. We are currently working on version 2.0, sponsored by contributors on OpenCollective, which will include a one-click report and labels. There will also be some changes to the way you can export the Parts List. We will keep your suggestion in mind!

**Comment by ganafets82** [comment]
cool, thanks!

**Comment by bbeaulant** [comment]
Hi @ganafets82,

I've got a curious question. In what kind of situation do you need the total volume of a material independently of its dimensions ?

**Comment by ganafets82** [comment]
Hi,

1. If I want to know the total weight of the construction - this happens often in my work. (Given weight limits or if I aim for light builds or if I want to know the transportation weight from the material supply)
2. For price calculation. In Germany the construction timber is given by 1m³. If I have the total volume of all dimensions from one kind of wood, add 20% waste/cutoffs, I have a good price approximation.
In the company I sometimes work for, I use a software that gives a cutting list with total amount - They also use this number for price calculation. 
3. Quick comparison of wood amount in different building styles. (Same buildings, different construction method)
4. If you regularly work on similar projects, you might spot mistakes in an early stage, if you are far of with the wood amount.

If you plan to implement this, summary of each material and summary of all materials would be cool.

I have to say I use OCL for buildings. But it seems optimized for furniture. Works fine anyhow. 

BTW: this would be a nice extra to add a field for purchase costs. Easy if the price is calculated per volume. Harder to implement, if every dimension has its own price (like plate material).
I do not really need this, but I think this would be a nice feature for others.

**Comment by bbeaulant** [comment]
Ok thanks,

> [...] this would be a nice extra to add a field for purchase costs.

This is the main goal of the next "Report" feature we are working on for the 2.0 release.

> Harder to implement, if every dimension has its own price (like plate material).

Yes this is the main problem to solve ...

**Comment by ganafets82** [comment]
Ups, I just edited my post quite long during your answer...maybe read again :-)
