### ISSUE TITLE
Importing from file with a "+" sign in name on Windows fails

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#240]
When trying to import from a CSV file containing a "+" in the name, like `test+ with space.csv`, it fails with the message

  `No such file or directory @ rb_sysopen - C:/Users/martin/Desktop/test with space.csv`

The plus sign is still in the params in dialog.twig (line 128 JSON.stringify(call)), but has disappeared in import_controller.rb line 58, thus trying to load a file with a wrong name.

**Comment by mobilarte** [comment]
Replacing

`window.location.href = "skp:ladb_opencutlist_command@0/0/" + call_json;`

with

`window.location.href = "skp:ladb_opencutlist_command@0/0/" + encodeURIComponent(call_json);`

in dialog.twig, line 136, seems to fix the filename problem, but may have side effects.

**Comment by bbeaulant** [comment]
Ok, lets try :)
