### ISSUE TITLE
Importing from CSV fails with error

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#241]
When importing a CSV file, the following error is logged in the Ruby Console:

``undefined method `key' for "{}":String
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/importer/importer_load_worker.rb:113:in `block in run'``

The import tabs shows ``Unable to load the CSV file: undefined method `key' for "{}":String
Verify that you have selected the correct field separator.``

``importer_load_options.json`` should include a default column assignment for the mandatory fields. That assignment should be mentionned in the help string.

**Comment by bbeaulant** [comment]
The problem seems to be in the way it retrieve your defaults.
In you case {} is a string but should be a hash.

It works fine on my dev build. Even if `colomn_mappging={}` . Maybe something is deferent on windows ?

**Comment by bbeaulant** [comment]
It works without this error on Win7 SU14 too ...
![Capture d’écran 2021-02-08 à 12 40 22](https://user-images.githubusercontent.com/156056/107214908-e50d3f80-6a0a-11eb-8755-a9ac0c2bbf68.png)

**Comment by bbeaulant** [comment]
Is you CSV file special ?

**Comment by mobilarte** [comment]
No, CSV is not special, but the key was corrupt. Restored with

`Sketchup.write_default("ladb_opencutlist", "importer.load.option.column_mapping", nil)`

Cause for corruption unknown, but if it happens, this may be difficult for the user to fix. Maybe we need a global `Restore all defaults` that would erase defaults?
