### ISSUE TITLE
Cutting diagram 2D : empty sheets

### ISSUE THREAD

**Issue by bbeaulant** [lairdubois/lairdubois-opencutlist-sketchup-extension#243]
If you use **offcut sheet goods**, unused sheets contains only one cut and no part.

![Capture d’écran 2021-02-09 à 08 58 38](https://user-images.githubusercontent.com/156056/107333411-bc8e4f80-6ab5-11eb-8a57-d0a40ced04b7.png)

![Capture d’écran 2021-02-09 à 09 05 16](https://user-images.githubusercontent.com/156056/107333572-f5c6bf80-6ab5-11eb-8112-2635e86c11a9.png)

**Comment by mobilarte** [comment]
Yes, I noticed the bug yesterday. Fix will be commited shortly with clean-up of code.

**Comment by mobilarte** [comment]
Fixed and tested.
