### ISSUE TITLE
Feature Request - Cutting diagram only option

### ISSUE THREAD

**Issue by theone11** [lairdubois/lairdubois-opencutlist-sketchup-extension#245]
I am working on my first project using OpenCutList - **Excellent extension** !!!

The carpenter that I am working with only likes to use the cut diagram itself without all the information below.
The problem is that some information on the diagram is sometimes missing (dimensions) and not very clear (Edge Banding).

To "improve" this I though maybe you can add a **_"Diagram Only"_** option in the Cut Diagram Display options, which will do the the following:

1. Only show Cut Diagram (maximum size) with **all** dimensions (reduce font size for specific dimensions if needed)
2. Use different Edge Banding color (mmaybe green) - the current color (dark blue) is very similar to the cut color (light blue) and is hard to distinguish between the two.
3. Indent the Edge Banding color inwards by a few %.
4. Increase dimension font size
5. Remove trailing zeros in the dimensions for example 10.0000mm -> 10mm, 7.2000mm -> 7.2mm

See example of expected output:

![image](https://user-images.githubusercontent.com/3348953/107650985-b2bc4600-6c87-11eb-9558-f90ba36c0851.png)

**Comment by bbeaulant** [comment]
Hi @theone11,

Thanks to appreciate OpenCutList :)

The good news is that some of requested options already exists : 

- You can hide part list and show diagram only.
![Capture d’écran 2021-02-11 à 15 49 16](https://user-images.githubusercontent.com/156056/107652365-cadc9700-6c80-11eb-82ad-77499adc2539.png)

- You can change dimension format directly in SketchUp Model Options : 
![Capture d’écran 2021-02-11 à 15 52 02](https://user-images.githubusercontent.com/156056/107652785-3b83b380-6c81-11eb-8102-f3c0c223aff6.png)

Else,
- The color of edge banding is the unique color when you print diagram. And this color is the global color of edge banding in all the extension. It won't be a good thing to have a different color for diagram only.
![Capture d’écran 2021-02-11 à 15 55 06](https://user-images.githubusercontent.com/156056/107653084-8d2c3e00-6c81-11eb-8077-2388223ea4a2.png)
- "Increase dimension font size" and "Indent the Edge Banding color inwards by a few %." and "(reduce font size for specific dimensions if needed)" are multiple choice that don't nicely match together :). Hide "unit" and reduce the dimension precision from Model Infos panel and you will see more dimensions.

**Comment by bbeaulant** [comment]
Cutting diagram couldn't display all part data. It's not its goal. And in multiple case it's simply not possible.

That's why we are currently work on a way to print labels that can be glued on each part and that contains the data the user wants.

![Capture d’écran 2021-02-11 à 13 45 26](https://user-images.githubusercontent.com/156056/107653929-733f2b00-6c82-11eb-9a37-e5652f0b117d.png)

I hope it could solve your problem are your carpenter needs :)

**Comment by theone11** [comment]
Thank you for the fast and detailed response.

When I choose to hide part list and show diagram only and print then I get 2 sheets on the same page. Can it be configured that each sheet will stretched to full page size and have 1 sheet per page?

![image](https://user-images.githubusercontent.com/3348953/107677176-aabdcf80-6ca2-11eb-904f-4de0612ea1da.png)

**Comment by bbeaulant** [comment]
The short answer is "no". Currently sheet couldn't fill paper width on A3 landscape.

Even if in your case it seems to be a strange choice. Panels are displayed with fixed width because cutting diagram can contains multiple panel sizes. And we choose that proportion have to be maintained between each sheets.

Print sheet dimensions are currently defined to be able to display common sheet sizes on A4 portrait.

**Comment by bbeaulant** [comment]
Improvement will be done in the next major release to propose an option to force diagram to display full width.

![Capture d’écran 2021-02-12 à 08 16 32](https://user-images.githubusercontent.com/156056/107740179-c957b100-6d0a-11eb-8777-eb328dfa223c.png)

![Capture d’écran 2021-02-12 à 08 16 50](https://user-images.githubusercontent.com/156056/107740178-c8268400-6d0a-11eb-9ea6-4f95c00209d5.png)

![Capture d’écran 2021-02-12 à 08 17 12](https://user-images.githubusercontent.com/156056/107740174-c65cc080-6d0a-11eb-9a75-0a7b7a72aa15.png)

**Comment by bbeaulant** [comment]
Sorry, but we can't give you a release date at this time.

**Comment by theone11** [comment]
Wow, looks excellent. Thank you.
