### ISSUE TITLE
Switching Scenes should invalidate Report or notify user

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#268]
When selecting parts in a scene, the user gets prompted to regenerate the Parts List. But when he switches from one scene to another with completely different content, the Parts List and the Report do not notify the user.

Suggestion: make the first prompt less disturbing (no blinking) but make it happen for scene changes too!

**Comment by bbeaulant** [comment]
The only one thing that can "remove" the "Selection changed" popup is to stop to automatically use the selection. But uses by default the entire scene and selection on demand.
