### ISSUE TITLE
Issue on 2.0 cutting diagram

### ISSUE THREAD

**Issue by saraivinha85** [lairdubois/lairdubois-opencutlist-sketchup-extension#285]
![1](https://user-images.githubusercontent.com/8818035/112366945-434b6480-8cd1-11eb-8e05-c6145d4c942f.png)
![2](https://user-images.githubusercontent.com/8818035/112366962-46deeb80-8cd1-11eb-872d-eb6ff4629371.png)
![3](https://user-images.githubusercontent.com/8818035/112366972-48101880-8cd1-11eb-93c6-fc482a4a1ef7.png)

**Comment by mobilarte** [comment]
Hi Pedro,

Thank you for reporting this! Could you please reproduce the case with the Ruby console open? There should be a dump of the parts list. 
Does this also happen when you select a different Cutting Diagram configuration (like Advanced/Lengthwise)?

**Comment by mobilarte** [comment]
@saraivinha85 I can reproduce the case, with these offcuts it happens with all configurations.

I will investigate this and let you know.

**Comment by mobilarte** [comment]
@saraivinha85 This bug happens when the first offcut can hold parts, but the next offcut not. In that case I was wrongly making the offcut invalid when in fact it was just unused. Fix in PR #287.
