### ISSUE TITLE
Impression : En-têtes doublées lorsque le saut de page arrive en bas de page.

### ISSUE THREAD

**Issue by Guillaurent** [lairdubois/lairdubois-opencutlist-sketchup-extension#309]
Hello

Tout petit bug de rien du tout mais je le signale quand même (en français).
À l'impression des fiches de débit (superbe fonctionnalité), lorsque la rupture de page arrive en bas de page, l'en-tête de tableau est affiché en bas de page [Page 1] (pas très utile) et à la page suivante l'en-tête est superposée [Page 2].
[Feuille de débit.pdf](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/6561844/Feuille.de.debit.pdf)

**Comment by bbeaulant** [comment]
Salut !

Merci pour ce retour. Je l'ai en effet constaté aussi. Mais je n'arrive pas à lui trouver une solution. 
La génération du page à page est totalement gérée par le navigateur (Chrome) embarqué avec SketchUp et à part en jouant avec le CSS, on a pas trop la main dessus. Il semble que la coupure d'un tableau en milieu de Header avec des colonnes groupées lui fasse faire n'importe quoi.

A creuser encore plus donc ...

**Comment by bbeaulant** [comment]
Ce problème semble solutionné dans la dernière version de chrome embarquée dans SketchUp 2021.
