### ISSUE TITLE
The parts don't rotate for no grain setting

### ISSUE THREAD

**Issue by ziyadsaeed** [lairdubois/lairdubois-opencutlist-sketchup-extension#312]
My shoe cabinet is made of white chipboard with no grain. But opencutlist doesn't optimize the sheets. It should rotate a part but doesn't. I have selected All possibilities as preferred direction. I'm attaching the images of the two sheets.. A part E on the second sheet can be fitted in the first sheet as it has plenty of room. 
![shoerack_001](https://user-images.githubusercontent.com/12503225/124362881-52876a00-dc51-11eb-88c8-e21164164768.png)
![shoerack_002](https://user-images.githubusercontent.com/12503225/124362882-54512d80-dc51-11eb-9240-b59d429b016d.png)

**Comment by mobilarte** [comment]
Hi Ziyad,

I see the problem! I assume you are using version 2.1.0 of OCL.

If you use the options **Medium** and **All Possibilities** you will obtain a different pattern. With **Medium** and **No Preference**, the result is an even better packing.

The best result is probably obtained when using **Advanced** and **Widthwise**, in that case only parts F will go into the second sheet.

So let me explain why this can happen.

1. There is probably no cutting diagram that can use only 1 sheet for your parts list.
2. With point 1. in mind, the algorithm will try to maximize the size of the leftovers to make them usable. Therefore it will rather put parts into a waste on sheet 2 than sheet 1 if the leftover in sheet 2 is smaller.
3. The placements into a sheet depend very much on the order in which they get placed (usually from larger to smaller, but not always) and the direction of the guillotine cuts (vertically first, then horizontally or vice versa).
4. We compute a fair number of possibilities, but not all, so we may miss a good solution.

Try all combinations of the parameters **Optimization Level** and **Preferred Direction**, sometimes even **Medium** gives better results than **Advanced**. In our case **Advanced** means more solutions computed and compared, but that leads sometimes to rather convoluted solutions.

**Comment by mobilarte** [comment]
No feedback
