### ISSUE TITLE
Cannot "Purge unused materials"

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#33]
When the unused material is selected in the Sketchup material tray, it cannot be deleted from the Materials tab.

- when it is not selected in the tray, it can be deleted
- when it is selected in the tray and it gets deleted from material property window (button at the bottom left) it works.

**Comment by bbeaulant** [comment]
The bad think is that we don't have the hand on this internal feature of Sketchup. OpenCutList just call this :

```
    def purge_unused_command()

      materials = Sketchup.active_model.materials
      materials.purge_unused

    end
```
