### ISSUE TITLE
Add hint to documentation that components need to be solid

### ISSUE THREAD

**Issue by kai-unger** [lairdubois/lairdubois-opencutlist-sketchup-extension#333]
## Background 
It seems OCL does only consider components with a volume (i.e. "solid components").

## Suggestion
In order to flatten the learning curve, the documentation (e.g. the basic example in the Wiki) should show a notice that flat components are not considered when generating the part list.

## Rationale
Sometimes the thickness or volume of parts is not that important (or even obstructive), for example when creating models for wall papering, plaster, carpets and other mainly 2-dimensional objects. 

Documentation should point out that such 2-dimensional models cannot be used with OCL.

**Comment by bbeaulant** [comment]
Yes view from OpenCutList, a part is **only** a 3-dimensional entity with not nul dimensions. This to be close to the reality and naturally exclude construction's lines, texts, dimensions, etc ...

Not necessary a "solid component", the important thing is the bounding box, not its content.

**Comment by mobilarte** [comment]
Added Alert Box in documentation about Components, Solid Components and the volume of the bounding box, [Components](https://docs.opencutlist.org/getting-started/components).
