### ISSUE TITLE
Does "Sorting of Parts by Thickness" make sense?

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#34]
Since parts are grouped by thickness, does "Sorting by Thickness" increasing/decreasing make sense?

Should the sorting by thickness apply to the groups of the Parts List? Is the sorting always done by "thickness decreasing" for groups?

**Comment by bbeaulant** [comment]
Sorting parts by thickness make sens only for Solid Wood materials.
For exemple you can have 20 and 22 mm in a group of solid wood of 27mm. This parameter permit to choice the sub tickness order.

> Is the sorting always done by "thickness decreasing" for groups?

Yes
