### ISSUE TITLE
Add Unit Cost to Report View

### ISSUE THREAD

**Issue by bjmiller121** [lairdubois/lairdubois-opencutlist-sketchup-extension#347]
I wonder if an option could be added to display the unit cost of a material alongside the total cost in the Report view. For example, adding a "$/fbm" column before the "Σ Cost" column. This would be a helpful reference if you need to add some material to your order while you're at the lumber yard picking out wood.

**Comment by mobilarte** [comment]
You mean adding it to the printed version of the report? 

The price per unit is available as a tooltip, but obviously not available on a printed version.

**Comment by bjmiller121** [comment]
Ah, yes. I didn't realize there was a tooltip, so thanks for pointing that out! I am referring to the printed version though. I think it could be a useful detail on a printed copy when you're either out in the shop doing some figuring or at the lumber yard.
