### ISSUE TITLE
Area of Parts in Reports

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#354]
In the Parts List the area of parts is displayed (not the area of used panels). Maybe this information could be added to the Report (net vs gross area).

https://opencollective.com/lairdubois-opencutlist-sketchup-extension/conversations/a-few-questions-about-the-program-dp8j3bqm

**Comment by bbeaulant** [comment]
Is part's area display in report interesting since we added the used part ratio un report weight and cost ?

**Comment by bbeaulant** [comment]
Fixed in 5.0
