### ISSUE TITLE
Importing New Material, not seen in Properties of Part

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#36]
When a Parts List has been generated, then we import a material from a .skm file, then go back to the properties of a piece in the Parts List, the new material is not available.

Should importing material generate a "change of the Parts List"?

**Comment by bbeaulant** [comment]
The bad news is that the internal importing materials function doesn't call the internal `onMaterialAdd` event on the MaerialObserver ...
