### ISSUE TITLE
Clean-up Translations

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#362]
Some things to do:

. closing sentences with a period (key:is_part_selection)
. check for keys that are no longer used (tab.cutlist.option.property_name)
. check similar sentences (key:is_part_selection, key:is_group_selection)

Write short memo for translators to help them verify stuff.

**Comment by bbeaulant** [comment]
> . closing sentences with a period (key:is_part_selection)

You are right.
And I remove the unnecessary "italic" style.

<img width="1566" alt="Capture d’écran 2021-11-25 à 07 33 44" src="https://user-images.githubusercontent.com/156056/143391689-f46bee01-3555-4de4-86a9-75cec79ab835.png">

> . check for keys that are no longer used (tab.cutlist.option.property_name)

This key is used here :)

![Uploading Capture d’écran 2021-11-25 à 07.26.05.png…]()
