### ISSUE TITLE
Description of Component can be changed, but not Instance

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#37]
In the Properties of a part, the "description" can be changed, but not the "instance".

Should a comment in the window indicate that it can only be changed in Sketchup?
In the extension "description" corresponds to "Definition" of Sketchup, may that confuse the user?

**Comment by bbeaulant** [comment]
A part is a **group** of instance with the same definition, dimension and material. Then it not possible to change the name of a specific instance.

**Comment by mobilarte** [comment]
Yes, this is exactly what I mean
fr: **Nom** in the extension, but **Définition** in Sketchup
en: **Description** in the extension but **Definition** in Sketchup

Should the label of the field be changed to avoid confusion?

**Comment by bbeaulant** [comment]
Yes, it's the 'definition' of the component, but le 'name' of the part.
You're right that definition could be less confused. But in cut list, does a new user understand what is definition ?

**Comment by ericjovis** [comment]
Les hommes de bonne volonté travaillent même le dimanche...

**Comment by bbeaulant** [comment]
@mobilarte, do you preconise to use the word **Definition** instead of Nom/Désignation in part properties window AND in cut list header column ?

@ericjovis bien entendu ;)

**Comment by mobilarte** [comment]
This is a tough call! I think it would sound awkward in the Parts List. Therefore I suggest you leave it as it is.
Sorry for bothering you with such small details.
