### ISSUE TITLE
Rough dimensions of sheet good parts not calculating properly?

### ISSUE THREAD

**Issue by d3rryc** [lairdubois/lairdubois-opencutlist-sketchup-extension#374]
Hey, there!

I'm running into trouble running the cutting diagram for my sheet goods. I backed all the way down to running a diagram for a single piece of plywood. The piece is small enough to fit on the material regardless of the part's orientation. As you can see, I have the oversizes set to zero in both directions, while both the kerf and trim sizes are small enough not to create issues, either. However, as you can see from my parts list, the rough sizes being calculated are WAY larger than they should be. 

Help?
Derry

![cutting diagram config](https://user-images.githubusercontent.com/97326933/148631447-dcc3bf3f-9f9a-46a0-9b9a-73c0b7e9954c.png)
![material properties](https://user-images.githubusercontent.com/97326933/148631448-ec502da3-c2b9-4d11-b3c1-08731bc2dfb2.png)
![oversizes](https://user-images.githubusercontent.com/97326933/148631449-377e2fdb-293e-40cb-b3ac-cfe638073714.png)
![parts list](https://user-images.githubusercontent.com/97326933/148631450-9afe47f0-62dc-4dbb-ba80-45907a81a8ff.png)

**Comment by bbeaulant** [comment]
Hi @d3rryc,

There's no miscalculation, but you define part oversize to 96" and 48" in material propreties.

![148631448-ec502da3-c2b9-4d11-b3c1-08731bc2dfb2](https://user-images.githubusercontent.com/156056/148636866-301e000b-a556-49c6-9595-8de3bc539c12.png)

Try to click on the following button to see this : 

![148631450-9afe47f0-62dc-4dbb-ba80-45907a81a8ff](https://user-images.githubusercontent.com/156056/148636924-8356a736-6098-4ff2-a7d5-6fd0660c141e.png)

Have a nice day,

**Comment by d3rryc** [comment]
Yep, that was my mistake. *facepalm*

Thanks for the help!
Derry
