### ISSUE TITLE
Add ability for parts to be cut from dimensional materials

### ISSUE THREAD

**Issue by DylanStracahn** [lairdubois/lairdubois-opencutlist-sketchup-extension#375]
I often use oversized dimensional lumber and cut multiple parts to reduce the cost. I ran into an issue where I need to cut a detail into a 1x6 board that ends up generating a "Cross Section Undefined" error. It would be great if the program would Identify that the cross section of 1x6 is needed to fit the part within and then show this on the cutting layout page. The part in question in the lower rail in a cabinet that has an arch detail cut into it. The final dimensions are 4-3/4", but would fit with the 1x6. 
![image](https://user-images.githubusercontent.com/97475440/148828948-4127f0f1-11bc-49ea-8523-cc5824a94716.png)
![image](https://user-images.githubusercontent.com/97475440/148829438-bf28787c-3083-4371-9505-bd12d72e68c9.png)

**Comment by bbeaulant** [comment]
Hi Dylan,

Sorry, but this is not the goal of the Dimensional material type. Cross section need to be exact.

OCL is not designed for your need to use oversized dimensional lumber.
