### ISSUE TITLE
Question: Saving Part Letters 

### ISSUE THREAD

**Issue by DylanStracahn** [lairdubois/lairdubois-opencutlist-sketchup-extension#377]
What would cause the part letters to change after they were saved? I do not have re-initialize selected, but occasionally the part letters will change. I can't find the root cause of what's happening. 

If I exit out of sketchup and reload opencutlist it will re-apply letters to some or all of the parts. If I switch scenes and come back it will also have the same effect. If I change anything in the model it will also have a similar effect.

**Comment by bbeaulant** [comment]
Hi,

Part's numbers are stored on component definition. But a single definition can represent multiple part (different scale, or material). Then multiple part number.
That why a stored part number is associated with the internal part identifier that is generated from "material", SketchUp internal definition ID, length, width, thickness and flipped state ([source](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/ed74c17e49f82a9388aa51478b2d113aebb3d77c/src/ladb_opencutlist/ruby/model/cutlist/partdef.rb#L92))

Unfortunately, with this strategy, if the size change, the part identifier change too. And then the stored number can't be retrieved.

**Comment by DylanStracahn** [comment]
> Hi,
> 
> Part's numbers are stored on component definition. But a single definition can represent multiple part (different scale, or material). Then multiple part number. That why a stored part number is associated with the internal part identifier that is generated from "material", SketchUp internal definition ID, length, width, thickness and flipped state ([source](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/ed74c17e49f82a9388aa51478b2d113aebb3d77c/src/ladb_opencutlist/ruby/model/cutlist/partdef.rb#L92))
> 
> Unfortunately, with this strategy, if the part size change, the part identifier change too. And then the stored number can't be retrieved.

**Comment by DylanStracahn** [comment]
I accidentally hit close. 

This is odd, because the parts that were re-assigned letters were not changed in any way. If I simply close Sketchup and re open it will change part letters.

**Comment by bbeaulant** [comment]
Strange ... a screenshot before and after ?

Caution that the model need to be saved to keep stored part numbers.

**Comment by DylanStracahn** [comment]
I'm not sure what to screenshot to show this happening, but yes the model is saved. I also find that if I add any new components to the model that it will change some things as well. It is very inconsistent though. Is there any way a feature to could be added to choose to reference the description or component name? I've had big issues where I start a project, cut parts in real life/label them, find an issue/need to make a change to piece of the model, change that in the model, then all of my labels get mixed up and no longer correspond with the labels on my parts in real life.

**Comment by bbeaulant** [comment]
Ok, but you **have to save part numbers too**. Else nothing is stored and new part or new part sorting can change each part number.

<img width="1228" alt="Capture d’écran 2022-01-14 à 18 33 59" src="https://user-images.githubusercontent.com/156056/149559906-ddcb91b3-1218-49be-ae74-9227a7e12076.png">

Only part number surrounded by a square are retrieve from stored numbers.

**Comment by DylanStracahn** [comment]
https://www.loom.com/share/52e0fad1c6ef472e864ef724536cdadd

**Comment by bbeaulant** [comment]
That's right that there is a problem there ...

**Comment by DylanStracahn** [comment]
Should I uninstall and try re-installing?

**Comment by bbeaulant** [comment]
No, I don't think that i cans sole the problem.
Could you send me your model and the way to reproduce this problem ?
(Use the **Report a Bug** button at the bottom of OpenCutList window)

**Comment by DylanStracahn** [comment]
When I click "report a bug" chrome opens and that's it. It doesn't direct me anywhere.

**Comment by bbeaulant** [comment]
It opens with a "mailto:" link. Use the email address in this link.

**Comment by DylanStracahn** [comment]
There is no email address or link. The window just opens. Please add email here.

**Comment by bbeaulant** [comment]
opencutlist @ lairdubois.fr
