### ISSUE TITLE
Opencutlist do not see components made by other plugins

### ISSUE THREAD

**Issue by Kirirru** [lairdubois/lairdubois-opencutlist-sketchup-extension#380]
Opencutlist do not see components made by [PomPi](https://sketchucation.com/plugin/2072-dezmo_pompi2016)
![2022-02-10_00-17-53](https://user-images.githubusercontent.com/98593696/153291755-43147dda-4266-4a90-9a95-f165ba721ae3.png)
![2022-02-10_00-18-24](https://user-images.githubusercontent.com/98593696/153291784-7f96f20a-d988-4eab-a7b0-fadbfb625345.png)

**Comment by Kirirru** [comment]
![2022-02-10_00-20-31](https://user-images.githubusercontent.com/98593696/153292008-13f15270-9d62-40b4-b658-df94499df2fd.png)

**Comment by Kirirru** [comment]
but when i recreate component from itself it works fine

**Comment by mobilarte** [comment]
Hi,

As you can see in the Inspector below the "pipe metric ..." there is no volume to this component. SketchUp has two different types of components: **component** without volume and **solid component** with a volume.

OpenCutList only considers solid components, hence it will not see the simple component with no volume. No volume means no thickness.

**Comment by mobilarte** [comment]
What I answered above is not entirely correct. Components with no volume, **but** with a bounding box that has a volume are also considered by OpenCutList.

**Comment by Kirirru** [comment]
Sorry, I dont understand.
![2022-02-10_00-51-29](https://user-images.githubusercontent.com/98593696/153296411-5cd09e8e-ac36-4621-8aa8-ed642e2b7c97.png)
this is same component but recreated from itself
![2022-02-10_00-52-11](https://user-images.githubusercontent.com/98593696/153296442-1b8c64a2-75f5-4ff9-a18d-4f2c72173205.png)
volume = 0m
What im doing wrong?

**Comment by mobilarte** [comment]
If you scroll down, you should see the part, but with no material applied to it. In the summary, OpenCutList tells you that it found 1 part. Apply some material to the component and it will appear.

**Comment by Kirirru** [comment]
it doesn't metter. OCL does not see component created by [PomPi](https://sketchucation.com/plugin/2072-dezmo_pompi2016) but it does when i recreated it manually

**Comment by bbeaulant** [comment]
Hi @Kirirru, could you please send a sample SKP file with the problem to opencutlist@lairdubois.fr ?

**Comment by Kirirru** [comment]
done

**Comment by bbeaulant** [comment]
Ok, this is just because PomPi component has "**cut opening**" attribute activated. 
Formultiple reasons, OpenCutList **ignore** components with this attribute.

<img width="1033" alt="Capture d’écran 2022-02-11 à 22 02 56" src="https://user-images.githubusercontent.com/156056/153669981-5fcfb922-70f1-4c06-add7-d591935cf962.png">

**Comment by Kirirru** [comment]
omg. THANKS A LOT! you saved me.
