### ISSUE TITLE
Warning when loading material from .skm file

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#390]
Using Sketchup 2022 I get this message in the Ruby console:

C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/materials/materials_import_from_skm_worker.rb:29: warning: URI.escape is obsolete

see also [warning: URI.escape is obsolete](https://stackoverflow.com/questions/68253213/warning-uri-escape-is-obsolete)

**Comment by bbeaulant** [comment]
I did some changes to fix it.

Need to be tested en Windows systems when using files with spaces.
