### ISSUE TITLE
"One Click to Prop" for Description and Edgebanding in Parts List

### ISSUE THREAD

**Issue by mauriciobellon** [lairdubois/lairdubois-opencutlist-sketchup-extension#415]
Hi there.

Before anything. You guys have been doing a fantastic job with the plugin it is by far the best of its kind.

May I suggest an UI improvement.

In Parts List when you have to edit the properties in the sheet goods tab of an specific part to add an extra layer for example, I have notice that I can access its tab directly from parts list by clicking in the thickness layers icon and it directly opens the modal for that property.

would be nice to have the same "one click to property" function added to que Description as well as the Edgebanding Icon in Parts List eliminating the need of going thuth tabs and making the job of editing whose props faster.

**Comment by bbeaulant** [comment]
Hi Mauricio,

Thank you very much for your feedback !

For your suggestions : 

It's already possible to click on the "Edge pattern" icon to directly open the edge banding tab of part properties.

<img width="1291" alt="Capture d’écran 2022-06-23 à 06 47 20" src="https://user-images.githubusercontent.com/156056/175212440-ee6d3391-d97a-4a11-8232-a95a6883c720.png">

Description has no icon. But part properties re-open automatically the last used tab. Then you only need to switch tab on the first part you click.

**Comment by mauriciobellon** [comment]
Boris,

You´re definily right about the edgebanding icon, sorry for missing that. 

I ve noticed the extra work as my current workflow isnt very smart and goes like this:

create all parts using the same dynamic component that I ve created 
select each part individualy
opens OC
generate part list for that one part
edit its props like Description, material, edgebanding and layers
select another part and start again

As a result I have to go thuth theses steps many times, including selecting the general tab to edit Description.

I'm yet to find a better way to work but guessing the smart thing to do would be remodeling my component to have all does props as atributes so I could edit while creating each part and use the OC panel just to check if things are good to cut

on that logic it cames to mind that would also be nice to have a part panel that auto updates with all OC part properties once you select only one part as OC have a much much better UI and integration with materials than what can be done with dynamic components panel <<< as far Im aware

man, sorry to boder you with all that and thank you for taking the time to anwser.

**Comment by bbeaulant** [comment]
Hi,

Part description can be edited from native SketchUp panel too.

<img width="1393" alt="Capture d’écran 2023-01-08 à 08 59 21" src="https://user-images.githubusercontent.com/156056/211186224-6b74e58a-fc19-4dd6-a25e-f19b8f4da231.png">

Edgesbanding and material could be applied on multiple parts in one click by selected them from part list and clicking on edit icon.

For OC, the best thing was to have correct attributes directly, no.
