### ISSUE TITLE
Not minimise when the main window is clicked

### ISSUE THREAD

**Issue by RebelSoftware** [lairdubois/lairdubois-opencutlist-sketchup-extension#425]
Is it possible to stop the opencutlist window from minimising every time the main sketchup window is clicked on

I don't use sketchup much and opencutlist even less. however I do find it a bit frustrating as I have two monitors and don't need it to minimise.

For those who prefer the current way minimising is it could be a simple checkbox in the preferences.

Great work, the software is quite impressive, as I said I don't use it much but its really neat to be able to have this plugin.

**Comment by bbeaulant** [comment]
Hi,

Thank you to appreciate OpenCutList !

OpenCutList **doesn't minimize automaticaly** except when you double click to use a material from Material's tab.

Could you please send us a video or describe more precisely this behavior ?

Regards.

**Comment by RebelSoftware** [comment]
Hi, Thanks for the quick response. For some reason I thought it was when I clicked on the main sketchup (2017 desktop) window, however I was wrong :( I can switch back and forth without an issue. 

When you click on "highlight part in model" (magnifying glass) in the parts list, it minimises. 

So what I was doing was highlighting the part. Clicking on the main window to take a closer look and then finding opencutlist had minimised. So I thought clicking on the main window was causing it, My Bad.

**Comment by bbeaulant** [comment]
Ok, in this case, just uncheck this option : 

<img width="1294" alt="Capture d’écran 2022-09-07 à 17 41 57" src="https://user-images.githubusercontent.com/156056/188921034-707b5d4e-5a0c-47a9-bcdf-37b5db334fef.png">

**Comment by RebelSoftware** [comment]
Oh. Sorry that I did not see that option. 

Problem solved.
