### ISSUE TITLE
Need information about optimisation algorithms

### ISSUE THREAD

**Issue by vishaljangid1729** [lairdubois/lairdubois-opencutlist-sketchup-extension#434]
Hi Team, 

I am curious and want to know which algorithm this extension uses for cutting 2D sheets that minimises the total waste.

**Comment by mobilarte** [comment]
The algorithm is essentially a guillotine bin-packing based on selecting the "best" solution from a set of heuristics.

**Comment by vishaljangid1729** [comment]
Does the best-fit solution always guarantee to minimize total waste?

**Comment by mobilarte** [comment]
Bin Packing is an NP-complete problem and thus no algorithm, except the exhaustive enumeration of all combinations, can give guarantee to find the solution with the minimal total waste.

In woodworking, being close to the minimum is usually sufficient. There are other important criteria than minimal waste, minimal cut length, largest leftover, least number of rotation of the panel when cutting, ...
