### ISSUE TITLE
I want to contribute a Vietnamese translation to the app OpenCutList

### ISSUE THREAD

**Issue by ngoctan091287** [lairdubois/lairdubois-opencutlist-sketchup-extension#448]
Hi, I'm in Vietnam and I want to contribute a Vietnamese translation to the app. I tried copying the english language file (ladb_opencutlist\js\i18n\en.js) and renamed it to vi.js. I tried translating a few words and running the app again but the app crashed. Can you guys help me out. Appreciation and thanks.

**Comment by mobilarte** [comment]
I have sent you a personal email with more information about the translation process.

**Comment by ngoctan091287** [comment]
Thank you.  I have submitted a project request on Transifex via the link: https://explore.transifex.com/opencutlist/opencutlist/ and hope to contribute a full Vietnamese translation to the application soon.  I am waiting for your approval on Transifex.  Appreciation and thanks.

**Comment by mobilarte** [comment]
You have been added as a reviewer/translator to the Vietnamese language for OCL on transifex!

**Comment by ngoctan091287** [comment]
Thank you very much.
