### ISSUE TITLE
Error when configuring Materials in version 4.0.1

### ISSUE THREAD

**Issue by Dmitriy-TamTK** [lairdubois/lairdubois-opencutlist-sketchup-extension#449]
After upgrading to version 4.0.1, I cannot configure the materials. This error does not go away after removing the plugin, restarting SketchUp 2018 Pro (and 2020 Pro) and reinstalling the plugin.
With the help of the "Coloring details" tool, I can add new material, but I can no longer edit it in the future.

![2022-12-17_10-46-10](https://user-images.githubusercontent.com/120774768/208231608-e185b9b6-deeb-4ae1-9456-00c906761af2.png)

![2022-12-17_10-38-13](https://user-images.githubusercontent.com/120774768/208231660-c4107cdc-c65a-447e-bc6c-caa6b353cd25.png)

![2022-12-17_10-48-51](https://user-images.githubusercontent.com/120774768/208231714-930017c5-3da1-44be-8e83-91ba28461fcb.png)

**Comment by bbeaulant** [comment]
Hi @Dmitriy-TamTK,

Can you please open the **Ruby Console** before generating the error and show me if there's some error messages into ?

**Comment by Dmitriy-TamTK** [comment]
This error is called on any project, even in a new one.

This screen was made during the calculation

![2022-12-17_11-03-15](https://user-images.githubusercontent.com/120774768/208232172-1f1261a1-bde2-4d3a-804b-2fb493fdbf8c.png)

This screenshot was taken after pressing the button Materials

![2022-12-17_11-04-12](https://user-images.githubusercontent.com/120774768/208232231-3f2cd7e1-99b2-4452-acd9-202e8172c8bd.png)

**Comment by bbeaulant** [comment]
It seams to be a problem when OpenCutList try to create a temp folder to place material's thumbnails. This folder already exists. But normally it shouldn't occur because OCL remove it before.

Maybe it can be solved by deleting the folder manually.
Type `File.join(Sketchup.temp_dir, "ladb_opencutlist")` in the ruby console and it will display the location of this folder.

**Comment by Dmitriy-TamTK** [comment]
It's decided! Deleted the "material_textures" folder and one file from the "material_thumbnails" folder. And when replaying the error, I added the extracted file back to the "material_thumbnails" folder, the error was repeated, and after returning to the "material_thumbnails" folder, the entire folder was automatically deleted, and after a few it was automatically created with the base files

The extra file had a higher resolution, but I didn't have time to compare the format.

![2022-12-17_11-22-04](https://user-images.githubusercontent.com/120774768/208233136-49aba909-b92b-4c7e-8dd6-c4e5651a0e5f.png)

**Comment by Dmitriy-TamTK** [comment]
Thank you very much for your prompt support!
