### ISSUE TITLE
Total cut length doesn't include trimming cuts

### ISSUE THREAD

**Issue by ArtVN** [lairdubois/lairdubois-opencutlist-sketchup-extension#469]
In cut report i'd like to see total cut length, that includes necessary trimming cuts (or checkbox in settings, that would add this)
For example
![изображение](https://user-images.githubusercontent.com/54498808/215260747-9b2e274f-2473-4045-889f-a5cac2b35964.png)
Length of cuts : 3,393 m (2800mm-2*10mm + 613mm)
But if I buy palels with cutting service, this will costs for me:
cost per m * 8,263m (2800mm + 2060mm + 2790mm +613mm) - at worst
cost per m * 6,826m (2800mm + 2800mm + 613mm +613mm) - at best

P.S. I read in other issue that ["By default we assume that panels need to be trimmed/squared"](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/issues/166#issuecomment-657457904). And for this reason I ask you to consider adding this feature

**Comment by bbeaulant** [comment]
Hi,

Hmm, yes but as you say it depends "when" your cut service do the trimming cut.
What value OpenCutList should use, the best or the worst ?
Or 2800 + 2070 (trim 2 sides of panel first) + length of internal cuts ... ?

**Comment by ArtVN** [comment]
It would be nice to see something like "trimming cut rule" in settings, but for first I can use a simpler (worst) value.
This will reduce the error in the calculation between me and cutting service (provided that we use the same cutting diagram)

**Comment by bbeaulant** [comment]
Anyway, your "best" calculation is not economically interesting for the cutting service. In my mind they will **never** do this choice.
Because cutting diagrams rarely contains only one part and for multiple parts it's largely time consuming to trim each border part individually. You have to turn them 2 times.

**Comment by bbeaulant** [comment]
Good news @ArtVN , OpenCutList 5.0 will count trimming cuts 😉
