### ISSUE TITLE
Hardware cost in Material Properties

### ISSUE THREAD

**Issue by ziyadsaeed** [lairdubois/lairdubois-opencutlist-sketchup-extension#494]
I cannot add hardware cost under the materials tab like i can for sheet goods.
The hardware cost is available under Part properties.
I use different materials for different hardware. for eg. Hinges will have different material compared to door handles.

**Comment by mobilarte** [comment]
The **Hardware** material is special. A price can only be configured on instances of a specific material. In your case, simply make several materials of type **Hardware** (door-handles, hinges, ...) and then assign a price to the instances of this material.

Price cannot and will not be configurable on the material of type **Hardware**.
