### ISSUE TITLE
Mirror cost

### ISSUE THREAD

**Issue by ziyadsaeed** [lairdubois/lairdubois-opencutlist-sketchup-extension#495]
Mirror or glass is cut from a large panel. But you don't usually buy the entire panel and just buy the size you need. Unlike sheet goods where you buy the entire sheet.
For things like mirror/glass I would like the cost to be of the actual area of glass used and not the cost of the entire panel. If i give it a cost of $per ft2. it calculates the cost of the entire panel.

**Comment by mobilarte** [comment]
In the next version there will be a summary of the actual cost versus the entire panel.
