### ISSUE TITLE
Open cutlist window does not launch on latest release of Sketchup 2023 after update

### ISSUE THREAD

**Issue by THEWOODPECKERCARPENTRY** [lairdubois/lairdubois-opencutlist-sketchup-extension#549]
Since updating to latest version of the cutlist with sketchup 23.0.0419 64bit the software no longer opens. 

I click on the icon and nothing happens. I have tried uninstall / reinstall etc but with no luck. Is anyone else finding this bug/

<img width="617" alt="image" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/135014659/c08a1020-0c1e-4894-8df8-2dd19cea39df">

**Comment by bbeaulant** [comment]
Hi,

Can you check if the OpenCutList dialog is not minimized in a corner of your screen.

Else, can you open the Ruby Console before trying to open OCL and watch if an error is displayed there.

Else, do you use 2 monitors ?

**Comment by bbeaulant** [comment]
> but have previosuly used an external monitor with my laptop.

OK, then OCL dialog is certainly on this screen.

Extension dialog positions are managed by SketchUp. And those position are stored in the `PrivatePreferences.json` file located in `%appdata%\SketchUp\SketchUp 2023\SketchUp\` folder.

Check in this file : 

<img width="454" alt="Capture d’écran 2023-05-30 à 12 06 14" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/3ba76c63-b6d5-434e-948d-fa1001710f64">

**Comment by mobilarte** [comment]
You may also try to `Reset Workspace` from the `Menu -> Preferences -> Workspace`.

**Comment by THEWOODPECKERCARPENTRY** [comment]
awesome managed to fix that, thanks 🙏

Kind Regards

Rob Smith
The Woodpecker Carpentry
M: 07983 499220
E: ***@***.***
W: www.the-woodpecker.co.uk<http://www.the-woodpecker.co.uk>
________________________________
