### ISSUE TITLE
Adding more pages/views to "draw"

### ISSUE THREAD

**Issue by Fr33man85** [lairdubois/lairdubois-opencutlist-sketchup-extension#555]
Hi,

like i mentioned in the past, here are one of my suggestions for better Workflow:

Would be good to have the ability to Add more then one view in the "Draw" submenu.
Sometimes i need not only a Isometric-View of a part, also a View from right, left or some other angle. 
Of course, it is possible now, but when exporting/printing, it will generate one seperate PDF/Layout-File for each view-angle. I would like to suggest, do consider a option to add a second or third or x additional view/page and get it exported/printed combined in one file.

I hope my explenaitions are good to understand.

Thank you

**Comment by bbeaulant** [comment]
Hi @Fr33man85,

I understand your need. But I don't want to go in this way. 
Multiple reasons :
- It's already possible through Layout and Copy/Paste. With more click, ok. But possible :)
- OpenCutList can't be a layout tool with full options. A lot of work to achieve it for just create a Layout clone ...
- Everything should stay as simple as possible.
- Time an money it could costs ... for a not a killer feature 😉

**Comment by Fr33man85** [comment]
I understand you too..
Just wanted to post my suggestions, without any expectations :)
If I never mention it, I definitely don't get it. At least there is a chance..
