### ISSUE TITLE
Directly drawn dimensions in "Generate draw"

### ISSUE THREAD

**Issue by Fr33man85** [lairdubois/lairdubois-opencutlist-sketchup-extension#556]
Another Point:
In my Case i usually have one "overview-view" in isometric view-angle, but i need some straight views for showing some measurements. For now this is only possible in the Layout-Export and add the measurements directly in Layout. (BTW: the button "Open Layout" in the Message-banner after export is done, is not working. There is also a Print-Issue: if the banner is still shown, when hit "Print". The Message will also be printed :D )

Sometimes this is a little bit "overpowered" to do it in Layout, especially if i have to take many measurements on many parts.. In this case it would be much easier, if the 3D-View in the "Generate Draw" would provide an option, where i can decide to put some additional measurements (with the native SU Measurement/Dimensions-Tools) or to have a checkbox what enable to show the already drawn dimensions on the highlighted Part in Sketchup (for now, the drawn dimensions-tool are not shown in the generated draw)

Thank you

**Comment by bbeaulant** [comment]
Quite the same answer than [previous issue](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/issues/555) : I don't want to create a Layout clone.

Keep in mind that drawing function is already a gift 😂

I know an all-in-one tool could be time save. But it's all about compromise.

> the button "Open Layout" in the Message-banner after export is done, is not working.

Are Layout files associated with Layout App on your computer ?
OpenCutList just call a `file:///path_to.fil.layout`. Does this kind of URL work from your browser ?

> There is also a Print-Issue: if the banner is still shown, when hit "Print". The Message will also be printed :D )

Interesting. Could you send a picture ?

> where i can decide to put some additional measurements (with the native SU Measurement/Dimensions-Tools)

So from the model itself, not OCL.

**Comment by Fr33man85** [comment]
> Are Layout files associated with Layout App on your computer ? OpenCutList just call a `file:///path_to.fil.layout`. Does this kind of URL work from your browser ?
> 
Yes, it is. Double click on a Layout-file will open layout


> Interesting. Could you send a picture ?
> 

![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/dd75e723-183d-45d4-9d5d-31e29ec8879b)

> 
> So from the model itself, not OCL.

Don´t understand. 
Do you mean, that i place my dimensions in SU and Print from SU, not from OCL?

I´am not so familiar with Ruby(?) and the capability´s of the underlaying API to SU, but i guessed, that this option would/could be maybe relatively easy to implement that the placed dimensions in the SU-Viewport also showing up in the Viewport of OCL. (like switch guidelines on/off in SU-Viewport.. but most properly i´am wrong

**Comment by bbeaulant** [comment]
Thank you for printing report of banner. It will be fixed in next patch 👍

> this option would/could be maybe relatively easy to implement that the placed dimensions in the SU-Viewport also showing up in the Viewport of OCL.

It may be but maybe only on particular conditions. Dimension **inside** the part for example.
