### ISSUE TITLE
Generate all at once

### ISSUE THREAD

**Issue by Fr33man85** [lairdubois/lairdubois-opencutlist-sketchup-extension#557]
Would be a great time safer (i hope so) if there would be a Button for a "complete Generate".
Means: One Button to Click, and get (based on predefined Settings) a finished File with the Partlist, Cutlist for every Material, Draws,..

**Comment by bbeaulant** [comment]
I understand the need too. 
But 2 reasons why it will not change 😉 : 
- OpenCutList was not internally designed for that. A lot of changes to do for a minor improvement.
- The time 🕦, all of these action can take a lot of time. How want to wait 5min in front of a progress bar.
