### ISSUE TITLE
Names in Titlebar for Components

### ISSUE THREAD

**Issue by Fr33man85** [lairdubois/lairdubois-opencutlist-sketchup-extension#558]
For now only the Title of the SU-File is in the Title bar of the generated drawings/lists.

Maybe important to Know: I/we don´t use your Plugin for Wood-working, we use it for Plant construction; so many Pipings, Racks out of steel, maintenance Plattforms for cooling towers.. ..

As example: The maintenance Plattform:
It is made out of different Materials like 100x100 rectangular Steel tubes with 3mm thickness, flat steel, round steel/tubes.. 
this material is assembled/welded together to bigger Parts. Some of them are mirrored. the whole assembly will be screwed together after everything is finished and galvanized.

What i wanna say: I have a "big" drawing in SU what shows the Plattform. Actually, it is grouped to a component. So, I export the Plattform to a SKP, which i open seperatly.
I select nothing, and generate my OCL for all shown parts/components and save the Part-Numbers to the components. 
Now i select only one assambly. Due the fact, that i saved the Part-Numbers, the Part "AE" at first generating will still be "AE" now. So i can regenerate the OCL with the Partlist, but only for this assambled Part. I do this for every assambly.. This is working without any flaw!

But in all my maybe 10 seperate OCL´s i will get, i have only the Title of the SU drawing, not of the name of the Assambly (maybe "Rail, left", "Rail, right", "Bracket, Main lower side",.... )

After printing out, and hand over to my Staff, this is sometimes very confusing, which part he holds in his hands.. 

So, the Title should be extended to the SU-Filename AND the component name, what is right now selected. (if one is selected)

Thank you

**Comment by bbeaulant** [comment]
It the header, you can see : 
- The model name
- The model description
- The Scene name
- The Scene description

<img width="1563" alt="Capture d’écran 2023-08-26 à 20 35 24" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/b582a5f1-4de5-475f-a26e-e7948d0402ec">

The best solution for you is certain to use named scenes.

**Comment by Fr33man85** [comment]
Thanks for you suggestions, but maybe we talking not about the same. I try to explain more:

![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/c788fd84-e85f-4247-96a0-7d5ccdfd06df)
Here you can see the whole Plattform.

I highlighted some of the mentioned Assambly´s. Overall 29 different Parts. 
All together are building the Plattform when screwed together. 
And each of the individuall Parts/Assambly´s are made out of the mentioned different Materials (like tubed steel, flat steel, a.s.o)

If I understand you correctly, then I see your suggestion as unnecessarily complex to create 29 scenes and to name them again as I named the components before. That doesn't make any sense to me

![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/a827ded9-1d8d-4add-8208-acaa742e21c6)

Each Assembly already have Definition-Names because they are also (nested) components. 
Reason: Some of them a mirrored and have to change together if a change is needed.

The Name of the Sketchup-File is shown in the header of OCL. That´s good and OK if i generate a "main Part list" without selecting anything in SU.
![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/82523c7a-37ce-4c64-b762-7a07d282bc67)

But not good, if i only generate a Partlist for one part:
![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/84f4e416-9ae4-4ea9-97e7-8b4e4ea92dbc)

Also no possibilitys to determine the part in the printed PDF
![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/ccc03011-cce1-4651-aa96-e501acb43233)

**Comment by Fr33man85** [comment]
I would like to add/improve my statement:

It's not that it's because I have to name them. It's more that I have to create the components anyway. Therefore, this is not only optional, but actually double the work to create the scenes as well.

**Comment by bbeaulant** [comment]
The component all the platform or only the blue selected entities on you first screenshot ?

Maybe the title could integrate the current editing path or selected "group" if only one is selected.

**Comment by Fr33man85** [comment]
Actually, the SU-File "_KT-Unterbau.skp" is a exported Component out of a much bigger drawing with the whole Cooling Plant.
So the path is like that:
Z100763_CustomerName_Coolingplant.skp
-> contains many Componets. also the "_KT-Unterbau" as a component. 
This component i exported by "right-click, export to.." to the File "_KT-Unterbau.skp".

That file, is exactly what you are seeing on the first Screenshot in which i selected some more components, it contains. 
Overall the mentioned 29 Components.. Each of them contain the Materials or, sometimes, also more nested components.

And again: i don´t know the capabilitys of the API.. but in any way also SU knows, which part i actually highlighting, because the Element-Info is showing me the attributes of it.. so, i guess, if there is any (definition-name)Variable what can be extracted to OCL for this, this should also be shown in the header. (if only one component is selected like in the last Screenshot "_KT-Unterbau, Geländer, kurze Stirn")

**Comment by bbeaulant** [comment]
I talk about the current editing tree path in the model structure.

Idea with instance names : 

<img width="973" alt="Capture d’écran 2023-08-26 à 21 32 57" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/ca4237bf-6081-4af3-b04d-b5839c7d17f5">

**Comment by Fr33man85** [comment]
Ah ok.. 
I closed my server connection for today.. i´ll give it a try tomorrow. 

Thank you

**Comment by bbeaulant** [comment]
> i´ll give it a try tomorrow.

This is not currently available. It's just an idea tested to my DEV build 😉

**Comment by Fr33man85** [comment]
Oh :D
Then i misunderstood you, sorry.

Yes, maybe not a bad idea. 
Is it also available for definition names instead of instance names?
i´am not sure about it. I did almost never use instance names till now.

Let me think about it tomorrow :D

**Comment by Fr33man85** [comment]
![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/0b8f0e44-458e-46af-9470-81749cf660e7)

I guess, your idea could be a good solution.

**Comment by bbeaulant** [comment]
Good, this will be available in the next 5.0.3 patch that should be published in few days.
We're just waiting for Trimble validation to publish it.

**Comment by bbeaulant** [comment]
5.0.3 is published. You can update and try feature.

Just be careful that this feature **only** uses **instance names**, not definition names of your components.
Because only instance can represent the true unique active path. And keep the user the choice of which part of the tree to use in this path.

**Comment by Fr33man85** [comment]
Thank you, i will test soon as possible. 👍

**Comment by Fr33man85** [comment]
Do i have to enable a special setting for it?
it doesn´t work for me.. 

![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/0b55701a-8142-43ae-97a9-ffd7a85c2e14)
Here i have a part (mirrored). 
One with instance Name: Tankunterstützung, rechts
The other one with: Tankunterstützung, links

both are from a component named: Erweiterung

but on OCL it still shows only the name of the overall skp-File:
![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/50385199/4ee1e920-a2c9-4f08-8f91-04f800258a38)

**Comment by bbeaulant** [comment]
This feature only changes the parts list title like in this screenshot [here](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/issues/558#issuecomment-1694488107)

This feature only displays the "active path", not the selected instance name.

The active path is where you are currently editing in the model tree. Double click on a group in your model to set it as active path.
