### ISSUE TITLE
bug: cannot find support forum

### ISSUE THREAD

**Issue by josh-m-sharpe** [lairdubois/lairdubois-opencutlist-sketchup-extension#563]
I see this after clicking: More -> Forum in the tool:

![OpenCutList_by_L_Air_du_Bois_-_4_1_1](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/39473/3929f8ff-c7d7-4eb9-ac8c-b75032c46dee)

Can't really find it on the google tool either or clicking around opencollective.com - probably some pebkac at work too :/

**Comment by bbeaulant** [comment]
Hi @josh-m-sharpe ,

Do you run the last 5.0.4 release ?

**Comment by josh-m-sharpe** [comment]
ah but the "Start a topic" button takes me to the forum....

**Comment by josh-m-sharpe** [comment]
> Hi @josh-m-sharpe ,
> 
> Do you run the last 5.0.4 release ?

Ah, I intentionally didn't upgrade because I was just trying to use the tool right now and not (potentially) have to learn about something new :)

**Comment by bbeaulant** [comment]
API was changed few month ago on Open Collective forum. That's why forum failed on old OpenCutList version. But we fixed it few version ago ...

> Ah, I intentionally didn't upgrade because I was just trying to use the tool right now and not (potentially) have to learn about something new :)

You can update without fear. Each version add new stuff, but old one continue to work in the same way.
