### ISSUE TITLE
Opencutlist will not open

### ISSUE THREAD

**Issue by maartenholst** [lairdubois/lairdubois-opencutlist-sketchup-extension#568]
Hi, 
I have a problem with the opencutlist not opening. While working in sketchup, I try to click the cutlist icon in my toolbar, it will think for a few seconds, but it will not run the program.
I tried,
reinstalling after uninstall through the extension manager and manually
Reinstalling SketchUp22 pro

I cant figure it out. And it kills me

Is anyone familiar with this problem or any suggestions?

**Comment by bbeaulant** [comment]
Hi @maartenholst,

2 Questions :
- Did you previously connect your computer to an external screen and move OpenCutList's dialog on it ?
- Is there minimized OpenCutList's dialog in a corner of your screen ?

**Comment by maartenholst** [comment]
Hi on question 1 yes and on question 2 no.

Could it be that hooking up 2nd screen I can find it again?

**Comment by maartenholst** [comment]
wow that did the trick! hooking up second screen and the program was running there!!
Thank you for resolving the issue

**Comment by bbeaulant** [comment]
Else, have to find the `PrivatePreferences.json` file and edit the `settings.dialog_left` to 0

<img width="600" alt="Capture d’écran 2023-10-04 à 15 37 39" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/03cf66be-0a0f-42f6-ad9a-4aa24432569d">

**Comment by maartenholst** [comment]
The second monitor did the trick. I travel between my home (second monitor)
and the workshop (no second monitor) and a hotel (no second monitor) so I
lost the extension for 2 weeks it really hindered me. But now that I know I
just have to remember to shift the window before moving the laptop.

Thank you so much.
