### ISSUE TITLE
BuG - gets stuck during cutting calculation

### ISSUE THREAD

**Issue by Kirirru** [lairdubois/lairdubois-opencutlist-sketchup-extension#630]
gets stuck during cutting calculation
![2024-02-25_22-07-05](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/8252c7e5-675d-401f-8f74-6e921da6a634)
[Bug.zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/14397513/Bug.zip)

**Comment by bbeaulant** [comment]
Hi,
Can you please open the Ruby console before opening OCL and send us the error that should be displayed there ?

**Comment by Kirirru** [comment]
[clippy.rb:180] : can't load C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/../../../bin/x86/lib/Clippy.dll
Error: #<NoMethodError: undefined method `c_get_cpath_area' for Ladb::OpenCutList::Clippy:Module>
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:91:in `get_rpath_area'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:203:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:202:in `map'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:202:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:180:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:180:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:65:in `_compute_part_projection_def'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:268:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:252:in `group_cuttingdiagram1d_advance_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:72:in `block in setup_commands'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:726:in `execute_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:1070:in `block in create_tabs_dialog'

**Comment by Kirirru** [comment]
![2024-02-27_19-41-39](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/020c7543-3085-43b0-bba4-326a5e0a260e)

**Comment by Kirirru** [comment]
[clippy.rb:180] : can't load C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/../../../bin/x86/lib/Clippy.dll
Error: #<NoMethodError: undefined method `c_get_cpath_area' for Ladb::OpenCutList::Clippy:Module>
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:91:in `get_rpath_area'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:203:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:202:in `map'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:202:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:180:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:180:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:65:in `_compute_part_projection_def'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:268:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:252:in `group_cuttingdiagram1d_advance_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:72:in `block in setup_commands'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:726:in `execute_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:1070:in `block in create_tabs_dialog'
"Add help menu!"
"create new"
"created"
#<Sketchup::Menu:0x0000025eea0bbfa8>
(eval):23: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

**Comment by bbeaulant** [comment]
Damned, it doesn't solve the problem on your computer :(

What version of Windows do you use ?

Else to bypass the error, Hide Shape of Part in Cutting diagram settings.

<img width="1299" alt="Capture d’écran 2024-02-27 à 16 27 02" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/60ecad85-32ba-4d79-b074-c2b3c6158eff">

But all new export 2D feature will continue to fail on your computer. For some unkonwn reasons the Clippy DLL can't be loaded on you computer ...

**Comment by Kirirru** [comment]
![2024-02-27_19-52-13](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/7a1bcfa7-b06d-4c4d-939a-be2609a21241)

**Comment by bbeaulant** [comment]
Yes, ALL new export features will **fail** on your computer.

**Comment by Kirirru** [comment]
what should i do?

**Comment by bbeaulant** [comment]
Check my comment 7 minutes ago :)

**Comment by Kirirru** [comment]
oh! sorry. Thx for help.

**Comment by bbeaulant** [comment]
Did you restart the computer after installing MS Redistribuable ?

**Comment by Kirirru** [comment]
Yes. Of course.

**Comment by bbeaulant** [comment]
Hmm 🤔

Can you type the following piece of code in the _Ruby Console_ and check if it returns `true` or `false` ?

`File.exist?("C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/../../../bin/x86/lib/Clippy.dll")`

**Comment by Kirirru** [comment]
File.exist?("C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/../../../bin/x86/lib/Clippy.dll")
=> true

**Comment by bbeaulant** [comment]
Ok thanks. So it's not the culprit 😕

**Comment by Kirirru** [comment]
all was fine until i get updated on 6 ver

**Comment by Kirirru** [comment]
i can give you an access to my working pc. via AnyDesk

**Comment by bbeaulant** [comment]
> all was fine until i get updated on 6 ver

Yes this occur on a new feature.
In 6.0, we add a link to an external library written in _C++_ : **Clippy.dll**. This library is responsible of computing fast 2D boolean operations. These operations are essential for detecting the shapes of the parts.
The problem on your computer is that this DLL failed to load. And I don't know why.

> i can give you an access to my working pc. via AnyDesk

Thank you but I don't know what I can do more.

`Clippy.dll `depends in the following system DLLs. Maybe check if these DLL are present on your computer ?

<img width="349" alt="Capture d’écran 2024-02-27 à 18 23 46" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/257f1b85-fed1-44cd-ae54-4bad97d02d37">

**Comment by Kirirru** [comment]
![2024-02-28_19-45-04](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/0470490a-2fae-4920-b83a-37d6709dd90f)

**Comment by bbeaulant** [comment]
Yes, Clippy is our DLL.

Check : 

- `c:\windows\system32\MSVCP140.DLL`
- `c:\windows\system32\CRUNTIME140.DLL`
- `c:\windows\system32\VCRUNTIME140_1.DLL`
- `c:\windows\system32\KERNEL32.DLL`

**Comment by Kirirru** [comment]
i have no CRUNTIME140.DLL

**Comment by Kirirru** [comment]
this one i have

**Comment by bbeaulant** [comment]
Ok, then dependencies not the problem too :(

**Comment by Kirirru** [comment]
what does it mean 

C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/../../../bin/x86/lib/Clippy.dll
Error: #<NoMethodError: undefined method `c_get_cpath_area' for Ladb::OpenCutList::Clippy:Module>

**Comment by bbeaulant** [comment]
Clippy.DLL contains shared methods written in C that Ruby can call. `c_get_cpath_area` is one of them. 
But as the DLL is not loaded, this shared method is undefined for Ruby.

**Comment by Kirirru** [comment]
i gues i found it
![Снимок экрана 2024-02-28 212718](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/2901e1f7-2e4b-40ed-a7fc-b5eab2d8ebb3)
is russian names are supported?

**Comment by bbeaulant** [comment]
Oh, well done ! That's it.

Yesterday I fixed this UTF-8 encoding problem. Can you try to install [this DEV version](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/6.1.0/dist/ladb_opencutlist.rbz) ?

**Comment by Kirirru** [comment]
It works fine. =)

**Comment by bbeaulant** [comment]
Yes !

**Comment by Kirirru** [comment]
NOPE! wait

**Comment by Kirirru** [comment]
OpenCutList 6.1.0-dev (build:202402281832) - ru - SketchUp 23.0.397 - win
#<Fiddle::DLError: can't load C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/bin/x86/lib/Clippy.dll>
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:89:in `rescue in block in dlload'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:86:in `block in dlload'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:77:in `collect'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:77:in `dlload'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:159:in `_load_lib'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:14:in `available?'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:29:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:65:in `_compute_part_projection_def'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:268:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:252:in `group_cuttingdiagram1d_advance_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:72:in `block in setup_commands'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:727:in `execute_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:1071:in `block in create_tabs_dialog'

**Comment by Kirirru** [comment]
it works. But with an error

**Comment by Kirirru** [comment]
![Снимок экрана 2024-02-28 215012](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/76822bcf-99ea-4257-ba3d-e8c8d38d3ee5)
same thing

**Comment by bbeaulant** [comment]
Yes, the error no longer blocks the execution in 6.1.0. But in fact cutting diagram switch Parts Shape display to hide.
The error is the same Clippy.dll can't be loaded.

**Comment by Kirirru** [comment]
look at path name

**Comment by bbeaulant** [comment]
Definitely it's an encoding problem ...

**Comment by Kirirru** [comment]
afk 20min

**Comment by bbeaulant** [comment]
Can you try to type in Ruby Console : 

`Ladb::OpenCutList::PLUGIN_DIR`

And after

`File.exist?(File.join(Ladb::OpenCutList::PLUGIN_DIR, 'bin/x86/lib/Clippy.dll'))`

**Comment by Kirirru** [comment]
Ladb::OpenCutList::PLUGIN_DIR
=> "C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist"
File.exist?(File.join(Ladb::OpenCutList::PLUGIN_DIR, 'bin/x86/lib/Clippy.dll'))
=> true

**Comment by bbeaulant** [comment]
Grrr, then no encoding problem there :(

And what respond : 

`Ladb::OpenCutList::Clippy.available?`

**Comment by Kirirru** [comment]
Ladb::OpenCutList::Clippy.available?
-------------------------------------------------------------
Please email the following error to opencutlist@lairdubois.fr
-------------------------------------------------------------
OpenCutList 6.1.0-dev (build:202402281832) - ru - SketchUp 23.0.397 - win
#<Fiddle::DLError: can't load C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/bin/x86/lib/Clippy.dll>
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:89:in `rescue in block in dlload'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:86:in `block in dlload'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:77:in `collect'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:77:in `dlload'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:159:in `_load_lib'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:14:in `available?'
<main>:in `<main>'
SketchUp:in `eval'
-------------------------------------------------------------
To resolve this issue, try installing the Microsoft Visual C++ Redistributable available here :
https://aka.ms/vs/17/release/vc_redist.x64.exe
-------------------------------------------------------------
=> false

**Comment by bbeaulant** [comment]
Try 

`Fiddle.dlopen(File.join(Ladb::OpenCutList::PLUGIN_DIR, 'bin/x86/lib/Clippy.dll'))`

**Comment by Kirirru** [comment]
Fiddle.dlopen(File.join(Ladb::OpenCutList::PLUGIN_DIR, 'bin/x86/lib/Clippy.dll'))
Error: #<Fiddle::DLError: No such file or directory>
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle.rb:47:in `initialize'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle.rb:47:in `new'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle.rb:47:in `dlopen'
<main>:in `<main>'
SketchUp:in `eval'
=> nil

**Comment by bbeaulant** [comment]
Arg ... maybe [Fiddle](https://ruby-doc.org/stdlib-2.5.6/libdoc/fiddle/rdoc/Fiddle.html) don't care about UTF-8 file path ...

Does this line : 

`Ladb::OpenCutList::PLUGIN_DIR.encoding`

Returns  ?

=> #<Encoding:UTF-8>

**Comment by Kirirru** [comment]
Ladb::OpenCutList::PLUGIN_DIR.encoding
=> #<Encoding:UTF-8>

**Comment by bbeaulant** [comment]
Ok, maybe we should try the correct encoding to use russian characters.

**Comment by Kirirru** [comment]
any tests before i go sleep?

**Comment by bbeaulant** [comment]
No, sorry, maybe tomorrow 😉

**Comment by Kirirru** [comment]
=) ok

**Comment by bbeaulant** [comment]
As far as I can test the DLL loader accept only ASCII path. That's the reason.

I did some tweak on DEV version (6.1.0 build 202402282207). 
If you can update and try it, let me know if it solves the problem 😉

**Comment by unknownexpert** [comment]
Hi, had the same problem. Installing the DEV Version fixed the problem @bbeaulant

**Comment by Kirirru** [comment]
![Снимок экрана 2024-02-29 142550](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/98593696/541ea8fd-ece6-4f19-a4a8-cc287d1e1e7d)

OpenCutList 6.1.0-dev (build:202402291035) - ru - SketchUp 23.0.397 - win
#<Fiddle::DLError: can't load Clippy.dll>
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:89:in `rescue in block in dlload'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:86:in `block in dlload'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:77:in `collect'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/fiddle/import.rb:77:in `dlload'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:175:in `_load_lib'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:18:in `available?'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:29:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:65:in `_compute_part_projection_def'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:268:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:252:in `group_cuttingdiagram1d_advance_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:72:in `block in setup_commands'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:723:in `execute_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:1067:in `block in create_tabs_dialog'

**Comment by Kirirru** [comment]
+ 6.1.0-dev (202402291035)

**Comment by bbeaulant** [comment]
Arg, can you retry with last build -> 6.1.0-dev (202402291235)

**Comment by Kirirru** [comment]
Nope =)

OpenCutList 6.1.0-dev (build:202402291235) - ru - SketchUp 23.0.397 - win
#<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and Windows-1251>
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:200:in `join'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:200:in `_load_lib'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:18:in `available?'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:29:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:65:in `_compute_part_projection_def'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:268:in `block (2 levels) in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:249:in `block in run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `each'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram1d_worker.rb:207:in `run'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:252:in `group_cuttingdiagram1d_advance_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:72:in `block in setup_commands'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:723:in `execute_command'
C:/Users/Кирилл/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:1067:in `block in create_tabs_dialog'

**Comment by Kirirru** [comment]
#<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and Windows-1251>

**Comment by bbeaulant** [comment]
Grrr ...

What's the return of this ?

`ENV['Path'].encoding`

**Comment by Kirirru** [comment]
ENV['Path'].encoding
=> #<Encoding:Windows-1251>

**Comment by Kirirru** [comment]
He got very sick. I'm going to bed. If I survive tomorrow, we will test again.

**Comment by bbeaulant** [comment]
Ok, I just commit a new buid (202402291643).
If tomorrow you can test. Get well soon.

**Comment by Kirirru** [comment]
Im AlivE! 
im ready

**Comment by bbeaulant** [comment]
Does the last build work for you ?

**Comment by bbeaulant** [comment]
> Yes it works. Finaly.

Yeah 👍!

> Maybe now I deserve to add the cost of cuts to the final estimate?

Best thing would be to open a new issue for that :)

**Comment by Kirirru** [comment]
[it was here](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/issues/379)
