### ISSUE TITLE
Import of materials and attributes

### ISSUE THREAD

**Issue by Kirirru** [lairdubois/lairdubois-opencutlist-sketchup-extension#641]
Hello, Boris.
is it possible to add materials via CSV? For example, I work with a lot of different materials. They have different costs, which change quite often. Is it possible to automate the process of updating materials from CSV with the binding name -> attribute (for example, price or weight.)

**Comment by bbeaulant** [comment]
Hi @Kirirru,

At the moment, I think this type of functionality takes OpenCutList too far from standard SketchUp operation. So this is not planned.

SketchUp and OpenCutList can import SKM file. **SKM files are just ZIP files** that contains XML files (material name and OCL attributes) and images data.
So you can write quite easily your own tool to create dynamically SKM files.

**Comment by Kirirru** [comment]
Okay, I'll do that. However, in my defense, I can say that you have created a wonderful tool that can do almost anything. For both design and accounting. Personally, I don't have enough little things like the cost of cutting (this is critical for working with metal) but I'm still coping. And importing some attributes without others. But you're the Boss here. If I do anything, I'll write here.

**Comment by Kirirru** [comment]
[Снимок экрана (13).zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/15248434/13.zip)
Okay, how about being able to select table fields that are attribute variables? at least a fixed set. Like the name and sizes that have already been implemented. Thus, you can import anything - the size of the workpiece, the price, the allowances, the length of the workpiece. It will be an amazingly flexible tool.

**Comment by Kirirru** [comment]
up

**Comment by bbeaulant** [comment]
It's would be a too complex solution to use part importer to create detailed material.

**Comment by Kirirru** [comment]
You have already implemented some of the functionality. it's great. But the rest is really missing. Good integration with price and size tables. After all, in this way it will be possible to generate the cost of the order in the table while the designer is working in a sketchup with data from this table.

**Comment by bbeaulant** [comment]
> You have already implemented some of the functionality.

Which ? It only creates a material from the a name.

**Comment by Kirirru** [comment]
ok! What about only one parameter "cost"? Is it possible?

**Comment by bbeaulant** [comment]
This importer is a part importer. Adding other material attribute than name can create inconsistent data (same material name and different attribute value).

As mention above, importing material is only possible in OpenCutList by importing SKM files. Those files contains all necessary data to create valid material. We don't want to reinvent this.
SKM files can be created by any external script. It's just XML packed with image in a ZIP file.
