### ISSUE TITLE
Depth looks reversed when exporting SVG

### ISSUE THREAD

**Issue by labelxyz** [lairdubois/lairdubois-opencutlist-sketchup-extension#645]
When I export an object to SVG, the depth/height of the paths are in reversed order. 
(I import the SVG file in Easel) Is there a way to reverse this?

I have tried all kind of things but nothing works...

First image in sketchup, second in easel...

![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/59361596/77beffd3-8672-4c35-8a65-229f4f0e4a60)
![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/59361596/e5f09670-a2c6-4152-ae8e-5adf65a8d5b4)

**Comment by bbeaulant** [comment]
Hi,

What merging Mode option did you use ?

**Comment by labelxyz** [comment]
Hi Boris,
I am not aware of using a merging mode. Is this in sketchup or in OpenCutlist?

**Comment by bbeaulant** [comment]
Hi, I'm talking about this parameter : 

![Capture d’écran 2024-05-23 073243](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/4ce13187-9ff1-4519-88ff-2fdca4b1a541)

As you can read in the documentation [here](https://docs.opencutlist.org/features/smart-export-tool#merging-mode), it changes the way depths of cut are exported.

Can you share your SVG ?

**Comment by labelxyz** [comment]
Thank you!

Aha, merging mode is called "ontleding" in the Dutch version. 
I've tried about everything to get the right file but without luck...

I must say that I am using OpenCutlist in a wrong way probably: I want to use my CNC to cut out one object only.... 

But, after a lot of trial and error I figured out that Easel uses the greycolor as depth indicator. 
This is interesting because than there are 256 depth levels. 
These levels are not absolute but always depending on the total height of je object.

Somehow the greytones from OpenCutlist are exactly the opposite of the sketchup heights.
I don't know if the greytones are related to the height of the faces in sketchup?

The top level face color should be #ffffff and the floorlevel = #000000.
![boris](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/59361596/656d4fde-eb26-429f-9da4-29ac2f70440e)


If the object is 40 mm high a face at 20 mm:
(25 / 40) * 256 = 128  hence the color must be #808080 
If the object is 50 mm high a face at 15 mm:
(15 / 40) * 256 = 96  hence the color must be #606060

I keep searching for solution. 

I have example files attached
[Boris.zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/15418941/Boris.zip)

**Comment by bbeaulant** [comment]
Hi,

Curently the depth color if from given part color in export form to white. [Code](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/e35d93fdefdb13bf5f053cb3987fc81e8d1512ee/src/ladb_opencutlist/ruby/helper/svg_writer_helper.rb#L176).

This is mainly beause it's the way the [Shaper Origin color encoding](https://support.shapertools.com/hc/en-us/articles/115002721473-Cut-Type-Encoding) works.

**Comment by labelxyz** [comment]
Thank you so much!
I can work with that.

Greetings
Eric Lugtigheid

Op vr 24 mei 2024 14:46 schreef Boris Beaulant ***@***.***>:
