### ISSUE TITLE
Edge Banding Name or Thickness on Parts List

### ISSUE THREAD

**Issue by pemitic** [lairdubois/lairdubois-opencutlist-sketchup-extension#646]
Hello,
Is it possible to add the name (or Thickness) of the banding in front of the icon in the 'Parts List', similar to what I added in the first image?
The printed Parts List should display it, as shown in the second image.

The Cutting Diagram has a pop-up window that displays the information, as shown in the third image, but it's not noticeable on the printed version (the last image).

![2024-05-24_152127](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/24562564/2b3898a2-22ad-4ab0-8745-7e6fd04eeaaa)

![2024-05-24_152320](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/24562564/9218f59e-8614-425f-9a8c-29b6c5a2a633)

![2024-05-24_152652](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/24562564/5aa63f51-7e81-4d25-8f2b-dcb4b0e0c977)

![image](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/24562564/0a58f880-443d-4eab-9c86-e84779040e25)

**Comment by bbeaulant** [comment]
Hi @pemitic ,

Did you try to enable edges column display from Parts List options ?
It presents name, thickness, width and color of the four edges in all tables.

**Comment by pemitic** [comment]
Thank You for your answer, I didn't saw that option.
That is great.
Best Regards
