### ISSUE TITLE
Visuels des pièces dans la fiche de débit

### ISSUE THREAD

**Issue by gares92** [lairdubois/lairdubois-opencutlist-sketchup-extension#652]
Bonjour Boris,

Je tiens tout d'abord à vous remercier chaleureusement pour cette excellente extension.

Je souhaite vous soumettre une proposition : ajouter les visuels des pièces sur la fiche de débit. Je pense que cela pourrait être particulièrement utile pour les poseurs sur chantier.

Bien cordialement,

<img width="1111" alt="Capture d’écran 2024-07-05 à 01 28 54" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/66022318/6a22fe7d-7c88-4421-9351-2a1ae82bca26">

**Comment by bbeaulant** [comment]
Bonjour @gares92 ,

Merci d'apprécier OpenCutList !

Ce que vous cherchez ne serait pas déjà résolu avec l'utilisation des [étiquettes](https://docs.opencutlist.org/features/parts/parts-list/printing-labels) ?
Etiquettes qui peuvent d'ailleurs avoir l'perçu de la pièce vu de face.

<img width="1262" alt="Capture d’écran 2024-07-05 à 08 45 47" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/8c419440-ecdb-4b34-8597-95197f1b5627">

L'avantage de l'étiquette est que c'est directement collé sur la pièce et pour l'utiliser ainsi, c'est beaucoup plus rapide sur chantier que de se référer à un fiche de débit.

Sinon, il est aussi possible de générer une liste des instances avec le visuels via des "fausses" etiquettes :)

Exemple : 

<img width="1262" alt="Capture d’écran 2024-07-05 à 08 49 02" src="https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/assets/156056/581b13c3-7de9-43d8-b82a-e57fa80b5876">
