### ISSUE TITLE
Esportare posizione componente

### ISSUE THREAD

**Issue by mazzo80** [lairdubois/lairdubois-opencutlist-sketchup-extension#653]
Salve a tutti Ho una domanda ....oltre al campo nome è possibile associare altri attributi del Dynamic Component?

**Comment by bbeaulant** [comment]
Currently it not possible.

**Comment by mazzo80** [comment]
Neanche nel esportazione del CVS con le formule?

**Comment by bbeaulant** [comment]
Maybe. It depends on how much money the users give us to be able to spend the time to develop it 😉

But in general, extracting "part position" is not possible on parts list because one part correspond to multiple instances that have each one their own position ...

**Comment by mazzo80** [comment]
Come faccio s fare una donazione per questo argomento?

**Comment by bbeaulant** [comment]
Click on the Sponsor + **Contribuisci** buttons.

<img width="1262" alt="Capture d’écran 2024-07-28 à 10 16 20" src="https://github.com/user-attachments/assets/7eb733c7-db17-442b-a3cc-6598ede9b086">

**Comment by mazzo80** [comment]
Grazie anche io nel mio piccolo voglio contribuire a questa fantastica applicazione

**Comment by bbeaulant** [comment]
Extracting [ComponentDefinition](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html) and [ComponentInstance](https://ruby.sketchup.com/Sketchup/ComponentInstance.html) properties will be possible in the next version 7.0 on several formulas.
