### ISSUE TITLE
No handling method was found for the event

### ISSUE THREAD

**Issue by wu1234a** [lairdubois/lairdubois-opencutlist-sketchup-extension#655]
In the jquery.ladb.dialog-tabs.js
at the line 268
`that.$element.trigger(jQuery.Event('maximizing.ladb.dialog'))`
can not find the event's method(maximizing.ladb.dialog) #

**Comment by bbeaulant** [comment]
Hello,

Can you give more details on the consequences of this problem?

**Comment by bbeaulant** [comment]
Close this issue : no details ☹️
