### ISSUE TITLE
About the default preset

### ISSUE THREAD

**Issue by Kirirru** [lairdubois/lairdubois-opencutlist-sketchup-extension#657]
Is there an option to set a customized preset by default? When cutting, I have to choose a preset for each position every time

**Comment by bbeaulant** [comment]
Yes, of course.

In each preset dropdown, you can copy current setting to Your default preset.

<img width="1262" alt="Capture d’écran 2024-09-04 à 11 55 55" src="https://github.com/user-attachments/assets/42a63b3a-012e-476d-b9e3-96d7a5f277e6">
