### ISSUE TITLE
material presets not working in new model

### ISSUE THREAD

**Issue by emrim** [lairdubois/lairdubois-opencutlist-sketchup-extension#666]
I created a material set and saved it as the "my-materials" set using "options/Presets/Save as."
The OCL material list is empty when I create a new model from scratch. Using the "options/Presets/Restore from", I see the   "my-materials" . But clicking on it, nothing happens, just a message appears: "The form has been filled with the prestige "my-materials"".
After that the material list ampty.

**Comment by bbeaulant** [comment]
Hello,

Material presets are associated with **one type of material**. So, for example, "Sheet good" presets are only visible if you create a new Sheet good material.

Can you share some screenshot  ?

**Comment by emrim** [comment]
Hi, thank you for the quick answer.
Here is the model where I created the mat. set:
![image](https://github.com/user-attachments/assets/de9e5b22-1a92-4b76-a7c4-2805e9e05f68)

And here I would like to use it:
![image](https://github.com/user-attachments/assets/32c2a612-0cbb-467f-8d5b-20473621bbf8)
![image](https://github.com/user-attachments/assets/086012b0-45a7-4b3e-a11f-584f52b69678)

AN I did not find the "falco-material.skm" file..

**Comment by bbeaulant** [comment]
Ok, there is some confusion.

Presets in Options tab only save and restore ... options. So here only how materials are sorted.
**It doesn't save and restore any material.**

Materials are out of OpenCutList. They are just native SketchUp materials.

To keep materials (and their settings) from one projet to an other you can use **native SketchUp Collection system**.
Find more details here : https://mastersketchup.com/ultimate-guide-to-sketchup-collections/
