### ISSUE TITLE
Display part shape

### ISSUE THREAD

**Issue by AhmedMixlogy** [lairdubois/lairdubois-opencutlist-sketchup-extension#681]
Diaplay part shape in cutting digram,
Does not work when parts have  edge band
I sugget to make it work with edge band, it may display & calculate edge banding only in outter rectangle shape,
Display part shape even in a simple graphic is important for idefing the shaped parts among other parts 
Thank you for this great project

**Comment by bbeaulant** [comment]
Parts shapes are not displayed only if there is a reduction with the edge bands.
Without this reduction they are displayed well.

Displaying part shape only for rectangular parts could be confusing.
