### ISSUE TITLE
Just an Idea Modifier des cotes dans la fiche de débit

### ISSUE THREAD

**Issue by hedjour** [lairdubois/lairdubois-opencutlist-sketchup-extension#84]
Bonjour,
Une idée peut être impossible à mettre en place serait il possible de modifier des côtes finales dans la fiche de débit ?
(J'ai un doute de t'avoir déjà posé la question, si oui tu m'en vois désolé).

**Comment by bbeaulant** [comment]
Salut,

Pour que ça change la taille dans le modèle ?

**Comment by hedjour** [comment]
Oui, je te pose la question par apport à mon plan de lit je me suis aperçu que mes planches ne sont pas assez épaisse du coup changer la valeur dans la fiche de débit et que ça le change dans le modèle est plus simple et sûr que de le changer en déplaçant des faces.

**Comment by bbeaulant** [comment]
Haha ... c'est un logiciel de dessin paramétrique qu'il te faut. Pas Sketchup ;)

**Comment by SlyLaM** [comment]
Bonjour,
Je suis débutant et sur sketchup et sur le bois ...
Mais n'empêche ;)
Ca pourrait être pas mal de pouvoir changer les côtes même sans qu ca change dans le modèle.
Je m'explique, je suis en train de réaliser un modèle d'ossature bois. Dès que j'incline certaines pièces, les cotes au lieu d'être d'une épaisseur de 45mm, passent à ~45mm. Du coup dans les listes, les pièces en 45mm et celles en ~45mm sont séparées. c'est très gênant.
Peut-être y a-t-il déjà une solution que je ne connaît pas ...

Merci!

**Comment by bbeaulant** [comment]
@SlyLaM, il n'est pas normal qu'une rotation de tes pièces fasse changer la côte.
Ce qu'il faut bien voir, c'est que le plugin utilise la boîte englobante pour mesurer la taille des pièces. Cette boîte on peut en avoir un aperçu quand on sélectionne la pièce dans le modèle. Ce sont les traits bleus.

Ca serait long à expliquer ici en quelques mots, mais ce qui est important, c'est que dans la composant de la pièce, le repère soit orienté avec les axes sur les trois dimensions de la pièce et non pas par rapport au système d'axe du modèle.

![capture d ecran 2018-11-29 a 11 09 41](https://user-images.githubusercontent.com/156056/49214593-4ebf4700-f3c7-11e8-8f23-b8462b2c39e9.png)
