### ISSUE TITLE
Measures not being saved

### ISSUE THREAD

**Issue by JumpingCap** [lairdubois/lairdubois-opencutlist-sketchup-extension#85]
Hi three, there seems to be an issue with configuring materials. After assigning a material to a component in sketchup I open OpenCutList and want to configure the size of the sheets. But after entering ie 1000x600 mm the size does not get saved.
Am I doing something wrong?

![screenshot 1](https://user-images.githubusercontent.com/1681337/47771509-d9872600-dce3-11e8-8b6d-16cf60660fec.jpg)
![screenshot 2](https://user-images.githubusercontent.com/1681337/47771510-d9872600-dce3-11e8-81b3-e99bafb58672.jpg)

**Comment by bbeaulant** [comment]
Hi JumpingCap,

You need to use a X to separate values and not a * (star). Like in the placeholder.
