### ISSUE TITLE
Ajout de "Available Sizes" dans "Dimensional" ? 

### ISSUE THREAD

**Issue by SlyLaM** [lairdubois/lairdubois-opencutlist-sketchup-extension#87]
Bonjour,
toujours dans mon projet d'ossature, je me disait qu'il manquait Available Sizes quand on choisi comme type de matériaux Dimensional. En effet, on peut paramétrer les sections disponibles mais pas les longueur.
Du coup j'ai changé mes matériaux en Sheet Good, choisi 45mm Thickness pour l'ossature puis dans Available Sizes la largeur et la longueur des bois d'ossatures vendus par mon fournisseur.
Ca me permet aussi de savoir comment couper pour éviter les chutes et commander exactement ce qu'il me faut.
Est-ce qu'il serait possible de rajouter ces fonctions dans "Dimensional" ?

Merci !

![capture d ecran 2018-11-28 a 14 09 42](https://user-images.githubusercontent.com/40861800/49153885-50c9cd00-f317-11e8-86a2-281541461b54.png)

**Comment by bbeaulant** [comment]
Bonjour,

Oui, le calepinage 1D (calepinage des barres) était au programme, et puis par manque de temps, nous ne l'avons pas intégré. (ce projet est réalisé bénévolement)
Disons que la solution que tu proposes est un moyen de contourner ce manque. Mais le rendu graphique n'est pas optimal.
Une boîte par barre devient très lourd si le projet est complexe. Et donc plutôt que de proposer une solution non abouti, il nous a semblé préférable de ne pas la proposer.

**Comment by DTownSMR** [comment]
_[pardon my non-existent French abilities. I hope I'm commenting on the right issue.]_

I too would like to see the ability of Open Cut List to be able to display cutlists for dimensional lumber. As well as calculating how many of each length of lumber to buy from my local supplier.

If my understanding of the Google translation of the above comments is correct, I would agree with the hesitation that a single board per bar would be unwieldy in a big project.

Excuse the ugly mockup below but I'm wondering if it would be possible to have a single bar for a given length of dimensional lumber only showing the (n) of unique cut diagrams needed. Only additional bit of information to the current listing would be the number of boards needed to be cut for each unique diagram.

_(just pretend that the 3rd & 4th entries are unique LOL)_
[crude mock-up](http://srussell.net/uploads/pics/OpenCutList/dimensionLumberMockUp.png)

Alternatively, even a total on the parts list dialog of how many boards (of a pre-specified length) of lumber could be helpful.

Thanks in advance for any consideration!

p.s. I'll try and get up to speed on Ruby and this project so I maybe able to contribute at some point but I've only dabbled in Ruby in a "Hello World" kind of way. :-)

**Comment by bbeaulant** [comment]
@DTownSMR, thats a good idea. Maybe we will plan it in a future release ... :)

**Comment by CyberBLN** [comment]
I started to implement the "cutlists for dimensional lumber" enhancement some days ago.

One question I have regarding standard panel sizes:

If I select "None" as standard panel size and also not added scrap sheet goods, the cutlist will not show up because there is nothing where the parts can be cutted from (internally the list of bins is empty). From my point of view it would be better than to add all standard panel sizes as bins of type Ladb::OpenCutList::BinPacking2D::BIN_TYPE_AUTO_GENERATED and use the bin packing lib the pickup the best matching size(s). Is there any reason against changing the current behavior this way?

**Comment by bbeaulant** [comment]
> I started to implement the "cutlists for dimensional lumber" enhancement some days ago.

Hmm, @mobilarte and I are currently working on this feature in branch https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/tree/Packing1D few weeks ago.

**Comment by CyberBLN** [comment]
> 
> 
> > I started to implement the "cutlists for dimensional lumber" enhancement some days ago.
> 
> Hmm, @mobilarte and I are currently working on this feature in branch https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/tree/Packing1D few weeks ago.

I reviewed your changes and in general I did the same. One thing I made different: I don't splitted the cutting list in a 1D and 2D version because there are not enough differences from my point of view. In the german translation I found some minor things that should be changed (Masse -> Maße f.i.).

What is the current state @bbeaulant, is it ready for testing?

**Comment by bbeaulant** [comment]
> I don't splitted the cutting list in a 1D and 2D version because there are not enough differences from my point of view.

We prefer to write a specific algorithm for 1D and 2D. And in this case option could be diffrent and more appropriated.

> What is the current state @bbeaulant, is it ready for testing?

Arf, due to our lack of time its WIP currently. The result is only displayed in ruby console.

> In the german translation I found some minor things that should be changed (Masse -> Maße f.i.).

You can propose a PR for this :)

**Comment by bbeaulant** [comment]
Done in the next 1.9 release.
