### ISSUE TITLE
Merge items (with the same dimensions)

### ISSUE THREAD

**Issue by wawont** [lairdubois/lairdubois-opencutlist-sketchup-extension#88]
Salut,

It would be great to have a function (option) of counting elements of the same size (but different names) and export them to the parts list.
Thus several lines will be merged into one with a total amount.
Now:
![count](https://user-images.githubusercontent.com/23648367/49358656-ff9a4e80-f705-11e8-9f1c-4ded4063b35c.png)
I want to:
![count_want](https://user-images.githubusercontent.com/23648367/49358734-4e47e880-f706-11e8-8e72-4e132ba0f50c.png)

Thanks for the plugin!

**Comment by bbeaulant** [comment]
Hi,

I understand you need, but I think this feature can bring misunderstanding to users. Same size part's name will be completly hidden by the groupping and only one name stay visible.

In your case, I recommend you to use the sort feature to have the parts with the same dimension in successive lines. This doesn't group parts, but it more readable to see same size parts.

![capture d ecran 2018-12-03 a 09 07 19](https://user-images.githubusercontent.com/156056/49360923-e4661980-f6da-11e8-92ac-4c12c000df1c.png)

**Comment by wawont** [comment]
This could be an option, but I still thank you for the answer.

Tell me where in the code this could be implemented, maybe I will do it myself?

**Comment by bbeaulant** [comment]
This feature will be integrated in 1.7.0 !
![Capture d’écran 2019-05-31 à 07 19 46](https://user-images.githubusercontent.com/156056/58683378-8443ed80-8374-11e9-917d-9c2c71924568.png)
