### ISSUE TITLE
toggle rough dimensions when using sheet goods

### ISSUE THREAD

**Issue by roguecode42** [lairdubois/lairdubois-opencutlist-sketchup-extension#89]
when cutting sheet good i may not need to rough cut first... My layouts would be more efficient and accurate if i could turn this off when i dont require it.

**Comment by bbeaulant** [comment]
Hi @roguecode42,
You can layout with final sizes. Just put material length and width **oversizes** to **zero**.

![capture d ecran 2018-12-06 a 12 54 46](https://user-images.githubusercontent.com/156056/49582711-2d75d200-f956-11e8-8d5e-6c9255917fb2.png)

**Comment by roguecode42** [comment]
Thanks for the speedy responce. I misinterpreted those fields as over
sizing the sheet for some reason.
