### ISSUE TITLE
Cutting Diagram not readable

### ISSUE THREAD

**Issue by QJan84** [lairdubois/lairdubois-opencutlist-sketchup-extension#90]
This extension is exactly what a woodworker needs. thanks for that!
A big problem: **the cutting diagram is unreadable**. See my screenshot:

![opencutlist-diagramm](https://user-images.githubusercontent.com/18675776/49896732-8cef4880-fe54-11e8-88f4-ae8c9aca929d.jpg)

The dimensions are not legible with small pieces. Is there a trick here?
I would also like to export the individual "Cuts". These are not visible in the PDF.

**Comment by QJan84** [comment]
"down scale the dimension font"
This could be the trick. I will try it.

Reading on mobile would be great! I have no ipad or pc in my woodshop :-)

**Comment by holle75** [comment]
Hi there, it´s me again. Thank you very much for the modifications concerning Volume in the last version!
I have a little problem with the cutting diagram for sheet material. Is it supposed to be so small? Please see attachement.
![opencutlist](https://user-images.githubusercontent.com/10577227/60807752-cb4cac00-a186-11e9-8b8a-5d13d413b971.jpg)

best
H.

**Comment by bbeaulant** [comment]
Hi, could you please give me your the version of Windows en Internet Explorer that run on you computer ?

**Comment by holle75** [comment]
the one machine is Win 10, the other Win 7. Both have "only" ie 11 installed cause i´m using firefox/waterfox.

**Comment by bbeaulant** [comment]
And as well on Win 7 or Win 10 the problem occur ?

**Comment by holle75** [comment]
I´m pretty sure i´ve never seen a bigger cutting diagram before (and was playing around quite often also on the win10 desktop) ... but not a 100% cause right now the desktop is 800km away. I´m on the notebook with win 7/ie 11 at the moment.

**Comment by holle75** [comment]
... any idea for a quick workaround (besides installing a newer, unneeded version of ie, clogging my tiny tiny HD on the notebook)? The sheets are desperately waiting to get cut :-)

... and i love the settings opencutlist offers to save time and material. I tried other extensions but there you have to do so many more cuts to get your pieces.

**Comment by bbeaulant** [comment]
I do no have a Win 7 with IE 11 setup to test it and try to fix the problem. The thing that I know is that on Win7 with IE 9, it works correctly.

**Comment by holle75** [comment]
unfortunately i can´t downgrade (there are some dependencies with some programs i use with IE/visual C if i remember right). I read something about problems in IE11 with displaying svg´s and a presetted height (from ie) of 150px. If you don´t change this preset in your css (or for the surrounding container), svg´s become mini.

**Comment by bbeaulant** [comment]
Can you try to test with the last 1.7.2-dev build available [here](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz) in the dist folder ?

**Comment by holle75** [comment]
already much more usable. Thank you. Wouldn´t it be great to use the whole 100% width of the window?

![opencutlist-dev](https://user-images.githubusercontent.com/10577227/60978166-07bc0b80-a331-11e9-8f32-6c8e33c3751a.jpg)

**Comment by bbeaulant** [comment]
It doesn't use the full size of the window to try to have the same aspect ratio between each panel (that can have different sizes). And in this case same part will be drawed at same size on different diagram.

The the full size (of the paper, not the screen) correspond to a panel of 3m wide.

**Comment by holle75** [comment]
Got you. Thank your for this explanation. And thanks again for the quick fix. I tried probably every extension out there because of the size-problem and, again, congratulations to your master-piece. All woodworkers worldwide should love you.

**Comment by Sarman28** [comment]
Hi, im having also problem in dimension. A panel/part with dimensions less than 204mm will not show in the cutting diagram. like if a part/panel is 200mmx1000mm, the dimension of this wont be shown in the cutting diagram. I already did some adjustment in my sketchup dimension sizes and units under model info. I will upload what my settings in model info are.
this is my problem
![opencutlist problem](https://user-images.githubusercontent.com/72462102/95237574-fb2ba900-083a-11eb-8d4c-d8d3ab793282.JPG)

my sample parts/panels
![opencutlist bug](https://user-images.githubusercontent.com/72462102/95237615-0979c500-083b-11eb-9d68-282525f936c1.JPG)


my model info setting
![model info dimensions](https://user-images.githubusercontent.com/72462102/95237643-0f6fa600-083b-11eb-98df-3c0afbb00400.JPG)
![model info text](https://user-images.githubusercontent.com/72462102/95237648-10a0d300-083b-11eb-9166-9fd446c19ab3.JPG)
![model info units](https://user-images.githubusercontent.com/72462102/95237651-11396980-083b-11eb-9b3c-68723fe40a9c.JPG)

by the way, the program is very great! i really like this problem big thanks to developers.

**Comment by bbeaulant** [comment]
@Sarman28, dimensions are hidden in cutting diagram if theres not enough room to display them around the part number/letter.
This is not a bug. The goal is to keep a clear diagram.
Activate the option to display part list of each panel to know dimensions of each part.

**Comment by Sady-CZ** [comment]
Hi there,
I have the same issue as mentioned above - cutting diagram for sheet material is tiny. I'm working with version 1.9.7 on Win10 with IE11.
Can you give me some advice pls?

![image](https://user-images.githubusercontent.com/73238365/96730974-0b08c880-13b7-11eb-9242-3d64b94df615.png)

**Comment by bbeaulant** [comment]
@Sady-CZ what I can see on you screenshot is not un issue.

If your sheet's size is really 450 mm x 300 mm, your parts should have a width around 10 mm, no ?

OCL present sheet with a fixed size (**1m = 280 pixels**). This size permit to see the difference between a sheet of 4500 x 3000 and 4500 x 300 just by watching it.

**Comment by Sady-CZ** [comment]
You are right - some of my parts have width only 20mm.
I understand your explanation, but did you consider any feature to zoom the diagram (not everyone is using only huge parts). :)

**Comment by bbeaulant** [comment]
> but did you consider any feature to zoom the diagram

Yes, it could be a new feature in the next major release (1.10) if we reach our **crowd funding**.
https://opencollective.com/lairdubois-opencutlist-sketchup-extension/updates/opencutlist-1-9-5-is-out-lets-climb-mont-blanc-together

**Comment by Sady-CZ** [comment]
Good to hear. You are doing great work -so I'm going to donate. ;-)
