### ISSUE TITLE
great extension! but how to..

### ISSUE THREAD

**Issue by sjasoo** [lairdubois/lairdubois-opencutlist-sketchup-extension#91]
Thanks for making this extension!
How to make a cutting diagram? I manage to make a part list. But how to go from there?

nevermind, I found out. sorry

**Comment by bbeaulant** [comment]
Hi and Thanks :)

First, you need to use material designed as Sheet Good on your pieces.

![capture d ecran 2019-01-27 a 08 54 59](https://user-images.githubusercontent.com/156056/51798382-4c376d00-2211-11e9-8b9c-1ac4c0469e78.png)

Second, just generate your part list and click on the Cutting Diagram button displayed on each group of Sheet Good material's pieces.

![capture d ecran 2019-01-27 a 08 56 15](https://user-images.githubusercontent.com/156056/51798396-87d23700-2211-11e9-9e6e-d299141a4afe.png)

Like you can see it in this video : https://youtu.be/FG4TFS1hmd4
