### ISSUE TITLE
Thank you! ... but volumes do not show

### ISSUE THREAD

**Issue by holle75** [lairdubois/lairdubois-opencutlist-sketchup-extension#93]
Thanks again to the creator of this gem. No complaints here, but i´m wondering. In my case volumes never get shown. Does this has to do with MY components or is it not working (when we already have the dimensions, the math should be simple)?
Very useful to order/price wood by volume or calculate the weight for transport. Also a already calculated Total by Material by the extension would be amazing. 

best
H.

EDIT: i should add, i´m still using Sketchup 2016 Pro

![opencutlist](https://user-images.githubusercontent.com/10577227/53683825-c9b93600-3d05-11e9-8443-2060592a7254.jpg)

**Comment by bbeaulant** [comment]
Thank you @holle75 😉 
Currently, volume in summary are only computed for _Solid Wood_ material.
But maybe it could be interesting to add it for the other types.

**Comment by holle75** [comment]
Ah, ok. I also put in, for example, boreholes or notches in my pieces of wood in SU. This way a solid component becomes a (non solid) component. Would be amazing if you would consider to implement a "volume" that´s just calculated by dimensions. Thank you anyways for this amazing extension. My whole organization of my shop depends on it.

**Comment by holle75** [comment]
Just for others with the same problem: I needed a day to figure out that volume has nothing to do with solid or non solid components but with defining the material as "solid wood" IN the extension.

**Comment by bbeaulant** [comment]
Ho sorry if me last comment was not enough clear. Yes Volume is currently computed only for "Solid Wood" type of material.
For example : 
![capture d ecran 2019-03-03 a 16 29 08](https://user-images.githubusercontent.com/156056/53697453-85936780-3dd1-11e9-914d-78a347459610.png)

In all the extension, parts a always considered as box. Even if the have a hole or whate ever. An this is because, SU is quite poor to understand more informations on parts. Its juste a set of lines and faces :)

Recently I take a look a the true volume function of Sketchup. But the internal feature seams to not consider resized component correctly. And then could return a bad value.

**Comment by holle75** [comment]
> 
> 
> Ho sorry if me last comment was not enough clear. Yes Volume is currently computed only for "Solid Wood" type of material.

> In all the extension, parts a always considered as box. Even if the have a hole or whatever. An this is because, SU is quite poor to understand more informations on parts. Its juste a set of lines and faces :)
> 
> Recently I take a look a the true volume function of Sketchup. But the internal feature seams to not consider resized component correctly. And then could return a bad value.

Yes, SU is complicated  with volumes. Especially when they are not "solid" -> no volume (entity info). Thats why i thought i have to solidify them for your extension to work.  And scaling, as you said, makes things even worse. 

Now everything seems fine. But unfortunately, if the material is "solid wood", volumes are getting shown ... but the very helpful column "length" becomes empty. Quite logic, but why not show both? This way you have to switch the material from "solid wood" to "dimensional" and back to get both data. For example when i have 50x100xLENGHT square wood in the scene it helps a lot to figure out how many meters you need. And the volume helps a lot for calculating the weight.

**Comment by bbeaulant** [comment]
It's easy to add raw volume in summary for all kind of materials. It's done in the "1.6.2-dev" release.
You can try it : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/master/dist/ladb_opencutlist-dev.rbz
And say me if it correspond to your needs ;)

**Comment by holle75** [comment]
Awesome! Thank you very much @bbeaulant . I´m pretty sure/hope also others might enjoy this new feature for the "dimensional" material.

**Comment by bbeaulant** [comment]
Nice ! Please take care that you now run a DEV release. And you meed to keep in mind that it would be important to replace it by the final one when it will be released. But I don't know when 😉

**Comment by holle75** [comment]
Yes, when it comes to computers i´m an old school manual guy. I do "installs/updates" by hand, name them accordingly "dev" and will not forget ;)
... mainly using portables for all my Software and go crazy about manufacturer imposed updates :D 

Thank you again.
