### ISSUE TITLE
Export summary issue in 1.6.4-dev realease

### ISSUE THREAD

**Issue by reshe** [lairdubois/lairdubois-opencutlist-sketchup-extension#98]
The summary information is exported correctly from what I can see, but the columns headings are missing the Thickness heading when exported and all other headings are shifted one cell backwards, so the exported file has header "Quantity" on the "Thickness " column, the "Length - raw (m)" is on the "Quantity" and so on to the end.

**Comment by bbeaulant** [comment]
Hi !
Ok, that « was » a bug. Try again with the last dev rbz available at the same place.
And you will see a 1.7.0-dev release with other fix and improvements that the 1.6.4-dev.

Regards.
